### ISSUE TITLE
Windows User issues with SSH connectivity on digitalocean

### ISSUE THREAD

**Issue by faisalbaz** [susanBuck/dwa15-fall2018#10]
Hi,
I have connectivity problems with digitalocean.com droplets. I have created new droplet following step by step instructions from class, digitalocean, and some google articles but I don't have any luck. I am able to create droplet and create SSH certificate. I have published it to my github repository for review. When I try to open my droplet using IP, it simple doesn't load. I read reviews, there are numerous users who are having similar issues. May I know if anyone of you are having these connectivity challanges? What steps did you take to connect? How were you able to connect to your git repository using SSH. 
I will appreciate your response.

Thank you.
V/R
Faisal Baz

**Comment by satyapalvadi** [comment]
@faisalbaz I am not sure if I understood you correctly. Do you have problems accessing the droplet via the ip address in the browser? Or was the problem connecting to github from the droplet?

**Comment by satyapalvadi** [comment]
I think you are missing a dot before ssh.
```
ServerAliveInterval 150
IdentifyFile ~/ssh/p1dwafbaz
```
should be
```
IdentityFile ~/.ssh/id_rsa 
```

( I used the default id_rsa in my env)

**Comment by susanBuck** [comment]
Piggy backing on @satyapalvadi's suggestion, your path should look like this:

```
IdentityFile ~/.ssh/p1dwafbaz 
```

(Includes the dot and *you*r key name `p1dwafbaz`, vs the default `id_rsa`)

**Comment by susanBuck** [comment]
@faisalbaz regarding the `Bad owner or permissions` error, please see my replies to this post: 
https://github.com/susanBuck/dwa15-fall2018/issues/12

Regarding your Droplet not loading, I think we may have to connect to troubleshoot this directly. Are you available Monday?

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
