### ISSUE TITLE
QueryException during migration - specified key too long

### ISSUE THREAD

**Issue by ningchen8743** [susanBuck/dwa15-fall2018#101]
Hello,

When I was running the php artisan migrate command, I came across an error:
![image](https://user-images.githubusercontent.com/38412041/48289476-9e9c9500-e43d-11e8-9e74-cdcda7740adc.png)
Has anyone seen this before? 

I compared the class notes from spring semester, I noticed there was an extra step before running migration:
![image](https://user-images.githubusercontent.com/38412041/48289518-cb50ac80-e43d-11e8-9d5b-24635f236aa0.png)
Do we still need to change the setting?

Thank you all!
-Ning

**Comment by ningchen8743** [comment]
Sorry! I got the wrong screenshot, the correct one is:
![image](https://user-images.githubusercontent.com/38412041/48289227-ad367c80-e43c-11e8-8998-e19103c82ba4.png)

I also noticed that in the spring semester's class notes, there is an extra set up before running migration:
![image](https://user-images.githubusercontent.com/38412041/48289315-ff779d80-e43c-11e8-86f3-c4613ca72ac5.png)

Do we still need to change the setting like this?
Thanks again!

**Comment by susanBuck** [comment]
@ningchen8743 That step was necessary in previous semesters because MAMP was installed with an older version of MySQL.

It shouldn't be necessary this semester.

Can you tell us if you're running MAMP or XAMPP and what version?

**Comment by susanBuck** [comment]
I just noticed in your screenshot that there's reference to XAMPP, so ignore that last question.

I'm going to go do a test on XAMPP now.

**Comment by susanBuck** [comment]
@Dory Yup - and it's only a problem in older versions of MySQL. For some reason I thought XAMPP had also updated to a newer MySQL (like MAMP did) and this would not be an issue this semester. I was wrong : )

Updating the notes to add this step for XAMPP users.

**Comment by susanBuck** [comment]
For reference, here's the direct link to the updated part of the notes that addresses this: 
https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/db-migrations.md#important-configuration-preface-for-xampp-users. 

I'm going to close this issue and make a separate pinned post to draw everyone's attention to it.

Thanks @ningchen8743 for drawing my attention to this!

**Comment by ningchen8743** [comment]
Thank you all! :)
