### ISSUE TITLE
MariaDB vs mysql

### ISSUE THREAD

**Issue by dnoren32** [susanBuck/dwa15-fall2018#105]
I'm running on windows and when I try to connect to mysql, I get connected with MariaDB instead (only on local). So I'm not sure what the best way to create the p4 table would be on the local server. I keep getting a `FAILED: SQLSTATE[HY000] [1049] Unknown database 'p4' (SQL: SHOW DATABASES;)"` when I try and confirm the connection. Here is how I'm attempting to connect to the database (per notes in [Database primer](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/db-primer.md))

```
λ C:\xampp\mysql\bin\mysql.exe --user=root --password=
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 62
Server version: 10.1.35-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Comment by susanBuck** [comment]
@dnoren32 - MariaDB is the "flavor" of MySQL that XAMPP ships with, so this is normal. 

Are you able to open phpMyAdmin and create the `p4` database via that?

With XAMPP running, it should be accessible via <http://localhost/phpmyadmin>.

Ref: [New database](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/db-primer.md#new-database)

**Comment by dnoren32** [comment]
@susanBuck I apologize for the delay, I'm just now being able to get back to this. I confirmed that I can create a p4 database on phpMyAdmin.

![image](https://user-images.githubusercontent.com/43149133/50027352-ec1a9d80-ffb9-11e8-813f-f1cfd8e80aa8.png)
