### ISSUE TITLE
'git' is not recognized - Windows Cmder

### ISSUE THREAD

**Issue by T-Waddell** [susanBuck/dwa15-fall2018#106]
Has anyone run into the error below when trying to run a git command on a local server? I've tried to run git status from both my foobooks directory and p3 directory. I'm not able to commit any changes.

```
'git' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by DoryAzar** [comment]
Are you sure you are in the directory root cause this is a typical error of a git not defined for the folder you are in.

**Comment by pausman** [comment]
The error message means that it does not find the program "git".   Could you have deleted the program?l Are you on a mac  or pc?  The instructions for installation are found here: https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/git-setup.md

**Comment by T-Waddell** [comment]
It looks like I no longer have git installed. My last commit was on November 7th. I am on Windows, and it came with the course build of cmder. I have no idea how it could have gotten deleted. The only major change I can think of was a Windows update. If anyone has any advice, I'm hoping to avoid this in the future.

When I start cmder, I now see this message, which I didn't before:
```
'C:\cmder-master\vendor\conemu-maximus5\..\init.bat' is not recognized as an internal or external command,
operable program or batch file.

C:\cmder-master>cd C:\xampp\htdocs\foobooks

C:\xampp\htdocs\foobooks>git status
'git' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by susanBuck** [comment]
@T-Waddell Can you try uninstalling and re-installing Cmder? 

[Here's the direct link to the class build of Cmder](https://github.com/susanBuck/cmder/archive/master.zip)

And here's the link to the relevant note set: [Windows Cmder](https://github.com/susanBuck/dwa15-fall2018/blob/master/command-line/windows-cmder.md)

If that doesn't work, let us know and we'll continue to troubleshoot.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
