### ISSUE TITLE
Views not working on production. htaccess or other problem? 

### ISSUE THREAD

**Issue by malrice** [susanBuck/dwa15-fall2018#108]
Hello, 
It looks like others have had this problem as well, but the solutions were never fully posted so I'm not sure how to correct it for mine. This is pertaining to the production display of my foobooks (found at http://foobooks.mallory-rice.me. The problem is that the homepage works and is formatted correctly, but when any of the links are clicked on, the pages don't exist where they're supposed to. However, if you go to a deeper page (such as http://foobooks.mallory-rice.me/index.php/books/search) suddenly there's the page. The page works completely normally on my local server. 

Any idea as to where I went wrong?

**Comment by DoryAzar** [comment]
you need to change the server url in the .env to indicate http://foobooks.mallory-rice.me

**Comment by malrice** [comment]
That's the thing, it's already pointing there. Here's the .env file on production (with key cropped): 
![screen shot 2018-11-26 at 6 35 22 pm](https://user-images.githubusercontent.com/42950461/49048804-29a1bd00-f1aa-11e8-8a18-5ec839f45551.png)

**Comment by susanBuck** [comment]
At first glance, it looked like URL rewriting isn't working properly on your server. I was thinking maybe `a2enmod` was not enabled (this is the necessary module routing uses, and was described in the notes on (prepping DO for Laravel)[https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/prep-digital-ocean-for-laravel.md])

But, I tested some of the routes you have in your P3 and they are working, e.g.:
http://p3.mallory-rice.me/test
http://p3.mallory-rice.me/practice/1

Given that, it leads me to think it's project config specific, not server config specific.

Can you share the full contents of your `/etc/apache2/sites-enabled/000-default.conf` file from your DO server?

**Comment by malrice** [comment]
Sure, take a look: 

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        <Directory /var/www/html/>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml $
        </IfModule>

</VirtualHost>

**Comment by susanBuck** [comment]
Hm, I don't think that's the full contents. Where are your virtualhost blocks?

**Comment by malrice** [comment]
Ha! You're right. Forgot to scroll. Here you go: 

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        <Directory /var/www/html/>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

</VirtualHost>

<VirtualHost *:80>
  ServerName p1.mallory-rice.me
  DocumentRoot "/var/www/html/p1"
  <Directory "/var/www/html/p1">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName p2.mallory-rice.me
  DocumentRoot "/var/www/html/p2"
  <Directory "/var/www/html/p2">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName foobooks.mallory-rice.me
  DocumentRoot "/var/www/html/foobooks/public"
  <Directory "/var/www/html/fooboks/public">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName p3.mallory-rice.me
  DocumentRoot "/var/www/html/p3/public"
  <Directory "/var/www/html/p3/public">
    AllowOverride All
  </Directory>
</VirtualHost>

**Comment by DoryAzar** [comment]
notice the typo in the Directory directive `fooboks` blink blink

**Comment by susanBuck** [comment]
@DoryAzar With the eagle eyes! : )

**Comment by malrice** [comment]
WOW! Let me change it and check

**Comment by susanBuck** [comment]
(Don't forget to run `service apache2 restart` after changing)

**Comment by malrice** [comment]
Worked like a charm! Thank you both so much, I was going crazy.
