### ISSUE TITLE
foobooks redo issue - fatal error when pushing

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#109]
Somewhere along the way, I missed some steps when creating the foobooks application. Rather than going through and figuring out at what point I'd missed things, I figured it would be easier to download the foobooks project, and start from the beginning so I could answer the query questions for this week's assignment. I get as far as the git push using `git push --set-upstream origin master` and then I get this: `fatal: unable to access 'https://github.com:baugh20s/foobooksNew.git/': Port number ended with 'b'` but I haven't been able to find anything online about that sort of error message. Any idea what's going on?

**Comment by DoryAzar** [comment]
Not sure I am understanding. If you want a local copy, why are you pushing to github?

**Comment by baugh20s** [comment]
Sorry! I realize my message was written hastily and wasn't very clear. I was able to resolve the issue though!
