### ISSUE TITLE
Foobooks errors related to WelcomeController

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#111]
I'm unable to create a seeder with the make:seeder command - I get an error message "Invalid route action: [App\Http\Controllers\WelcomeController].". I get exactly the same error message accessing Foobooks through local host (I can't). When I look in my Fooboojks directory, there is no WelcomeController. I'm not sure why and suspect it is accidentally deleted. Is reloading Foobooks and starting from scratch the only solution? I see baugh20s has attempted that. Would I be able to create or copy a new WelcomeController maybe?

**Comment by Sud-B** [comment]
I explored further and I find that there is no WelcomeController and the view is returned from the closure, so hopefully this error to tackle than I first thought. Any thoughts?

**Comment by susanBuck** [comment]
If you've lost your foobooks WelcomeController.php, you can just recreate it using the [WelcomeController.php found in my foobooks source code](https://github.com/susanBuck/foobooks/blob/master/app/Http/Controllers/WelcomeController.php).

**Comment by Sud-B** [comment]
Thank you!
