### ISSUE TITLE
Laravel X Vue.js (or other JS framework)

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#113]
Hey!

Just recently I've learned a bit of Vue, and was curious if anyone has experience using a JS framework like Vue, Angular or React in Laravel.  Immediately I noticed there is some competition between Blade templating and Vue syntax with the `{{ }}` notation.  I'd be interested in whether these frameworks play nicely in the Vue ecosystem.

Tks!

**Comment by susanBuck** [comment]
Here's some info about Blade & JS Frameworks, speaking specifically to the `{{ }}` notation overlap: https://laravel.com/docs/5.7/blade#blade-and-javascript-frameworks

**Comment by jessupjs** [comment]
Thank you!
