### ISSUE TITLE
problem with old on select

### ISSUE THREAD

**Issue by fpizzuta** [susanBuck/dwa15-fall2018#118]
If i include the old function in my option
`<option value='{{$game->game_id}}' {{old('game_id' == $game->game_id) ? 'selected' : '' }}>{{$game->gameName}}</option>`
 I get an error saying: 

> array_key_exists(): The first argument should be either a string or an integer (View: C:\xampp\htdocs\p4\resources\views\games\create.blade.php)

 
If I do this instead
`<option value='{{$game->game_id}}'>{{$game->gameName}}</option>`
the page loads and the form has a dropdown but I loose the prefill option on an incomplete form.

Any ideas?

Thanks

**Comment by DoryAzar** [comment]
Hmm the parentheses seems to be in the wrong place, yoh probably wanna try this instead:
`old(game_id) == $game->game_id) ? ‘selected’ : ‘’`

**Comment by fpizzuta** [comment]
OMG, i looked at this for an hour and missed the (). Thank you!
