### ISSUE TITLE
Query Issue with Search Feature

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#120]
Hi I am working on the search feature of my site, and I have the following code in the controller. I cannot seem to make the search feature work by getting the titles of the events from the database. Anyone have any tips? 
``` public function search(Request $request)
    {
        return view('events.search')->with([
            'searchTerm' => session('searchTerm', ''),
            'searchResults' => session('searchResults', []),
        ]);
    }

    public function searchProcess(Request $request)
    {
        $searchResults = [];
        $searchTerm = $request->input('searchTerm', null);
        $events = Event::all();
        if ($searchTerm) {
            if ($searchTerm) {
                foreach ($events as $name => $event) {
                    if ($event == $searchTerm) {
                        return $searchResults;
                    }
                }
            }
        } 
```

**Comment by DoryAzar** [comment]
Most likely unrelated to the code not working, but you have 2 if statements that are exactly the same, you should probably get rid of one.
Now back to debugging the error, it would help if we know more about the Event object structure. Could you please show us the results of `dump($events->toArray())`

**Comment by cpowell1** [comment]
Ah right, thanks... I got rid of the duplicate. Here are the results of the dump statement when I search using the above code.
<img width="469" alt="screen shot 2018-12-12 at 9 41 42 am" src="https://user-images.githubusercontent.com/35276882/49880644-3a7d4000-fdf2-11e8-8610-944f97402f71.png">

**Comment by DoryAzar** [comment]
Ok so now you need to fix your loop. You need to compare event_name to the searchFilter. So it should look like this:
```
foreach($events as $event) {
    if ($event->event_name == searchFilter) {
   etc...
}
}

**Comment by cpowell1** [comment]
Well I added that code, and included this, but it still isn't returning any results for a event I know is there. 

``` 
$searchResults = [];
        $searchTerm = $request->input('searchTerm', null);
        $events = Event::all();

            if ($searchTerm) {
                foreach ($events as $event) {
                    if ($event->event_name == $searchTerm) {
                        {
                           return $searchResults;
                        }
                    }
                }
            }
```

**Comment by DoryAzar** [comment]
ok loop is correct. Now searchResults is empty. So you probably need to push events into it.
So instead of doing `return $searchResults`,
do this: `array_push($searchResults, $event);`
Now if you print $searchResults, it should work.
