### ISSUE TITLE
Attempt to rename table gives syntax error

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#121]
I created a table with a name that does not become singular simply by removing the 's' at the end. The table name is 'hobbies' (which is 'hobby' in the singular). I figured rather than try to override the built-in functionality around singular and plural names, I would use 'hobbie' as the singular (for the model, and in the pivot table name), but I accidentally named the table contact_hobby. I'd like to change it to contact_hobbie but when I use the command provided in the Eloquent documentation, I'm getting a syntax error. Anyone know what might be happening?

This is the documentation: [https://laravel.com/docs/5.7/migrations#renaming-and-dropping-tables]
![screen shot 2018-12-11 at 7 20 46 pm]

This is the command and error I'm seeing:
(https://user-images.githubusercontent.com/20144373/49838940-ec792580-fd7a-11e8-9eb4-92a635a9356c.png)

**Comment by ccrane** [comment]
@baugh20s In your `Hobby' model class you the code below to set the name of your table;

`protected $table = 'hobbies';`

Also, I would suggest dropping the `migrations` table in your database and running your migrations from scratch.

**Comment by susanBuck** [comment]
@ccrane's solution works, but note that Eloquent is "smart" enough to make the conversion between hobbies <-> hobby.

(Tip: Read more [here](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/db-eloquent.md#eloquent-requirements) - look for the note on string helper functions `str_plural` and `str_singular`)

**Comment by baugh20s** [comment]
Ah, thank you, @susanBuck! I missed that before.
