### ISSUE TITLE
419 error when attempting to insert row/create record

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#123]
In setting up my create operation, I originally attempted to take the user to the new contact record once they submitted the form so they can see the details.

When I had difficulty getting that working (getting a 419 error), I couldn't figure out what the problem was so I decided to attempt to get it working the same way we did with foobooks - just to see if I could get something working - where it directs the user back to the list, but no such luck. Still getting the 419 (sorry, your session has expired. please refresh and try again).

![419 error](https://user-images.githubusercontent.com/20144373/49915036-a6e35800-fe61-11e8-8a91-f129cfe012a7.png)

My create.blade.php loads fine; I enter in the information, click submit, and get the error.

Here's the form action from the create.blade.php view:
`<form method='POST' action='/contacts'>`

And the route in web.php:
`Route::post('/contacts', 'ContactController@storeNew');`

And the function in the controller:
`public function storeNew(Request $request)
    {
        # Validate the request data
        $request->validate([
            'firstName' => 'required|string|between:1,75',
            'lastName' => 'required|string|between:1,125',
            'emailType' => 'required|string',
            'email' => 'required|email|between:7,100',
            'phoneType' => 'required|string',
            'phone' => 'required|regex:/(01)[0-9]{9}/',
        ]);

        $contact = new Contact();
        $contact->first_name = $request->firstName;
        $contact->last_name = $request->lastName;
        $contact->full_name = $request->firstName.''.$request->lastName;
        $contact->email_type = $request->emailType;
        $contact->email = $request->email;
        $contact->phone_type = $request->phoneType;
        $contact->phone = $request->phone;
        $contact->save();

        return redirect('/contacts')->with([
            'alert' => 'Your contact was added.'
        ]);
    }`

**Comment by DoryAzar** [comment]
2 reasons I could think of:
1) You forgot the csrf in your form or you are declaring it the wrong way
2) Your session is getting destroyed along in the process. Which can either be that you are destroying on purpose somewhere in your routes or that you are implementing authentification and you are logging out.

I would think it’s 1)

**Comment by baugh20s** [comment]
@DoryAzar It was the first one - thank you!
