### ISSUE TITLE
Seeding Error after trying to create pivot tables

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#124]
I created a pivot table for my categories. When I did the migrate:fresh then attempted to run db:seed, I received this error message. I cross-checked with the notes and the foobooks example, and I can't seem why it won't seed the 'type' column. Any ideas?
<img width="1140" alt="screen shot 2018-12-13 at 10 39 00 pm" src="https://user-images.githubusercontent.com/35276882/49983489-b9749480-ff28-11e8-925f-d72ffef51052.png">

**Comment by pausman** [comment]
Can you show us your CategoryEventTableSeeder file and the create_catergory_event_table migration file?

**Comment by cpowell1** [comment]
<img width="696" alt="screen shot 2018-12-14 at 11 04 26 am" src="https://user-images.githubusercontent.com/35276882/50016894-1d7e7380-ff90-11e8-9dcd-37ee48361eea.png">
<img width="709" alt="screen shot 2018-12-14 at 11 04 55 am" src="https://user-images.githubusercontent.com/35276882/50016898-1fe0cd80-ff90-11e8-8ceb-6b70eb9cd6fe.png">
<img width="621" alt="screen shot 2018-12-14 at 11 04 46 am" src="https://user-images.githubusercontent.com/35276882/50016904-2111fa80-ff90-11e8-8130-a4d423f43118.png">

**Comment by cpowell1** [comment]
This is my event model, but I also get the message that it is null.
``` class Event extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category')->withTimestamps();
    }

    public static function dump($events = null)
    {
        $data = [];
        # Determine if we should use $books as was passed to this method
        # or query for all books
        if (is_null($events)) {
            $events = self::all();
        }
        # Load the data array with the book info we want
        foreach ($events as $event) {
            $data[] = $event->event_name . ' on ' . $event->date . ' at ' . $event->time. ' at '. $event->location;
        }
        dump($data);
    }
} ```

**Comment by DoryAzar** [comment]
If you check your Event migration, does it have a column ‘type’. According to the error you are getting, it doesn’t.

**Comment by cpowell1** [comment]
I see what you are saying, when I had tried that prior, it gave me this error. I thought what you were saying made alot of sense, but there has to be something I am missing for it to throw the error. My github is https://github.com/cpowell1/p4 if that is easier to see this code... and thanks so much for the help. 
<img width="998" alt="screen shot 2018-12-14 at 6 34 43 pm" src="https://user-images.githubusercontent.com/35276882/50036515-f98e5280-ffce-11e8-8518-7581753d4a1c.png">

**Comment by DoryAzar** [comment]
Hmm that looks like a different error. Are you having that same error locally?
If you are not, then you might need to check the production database settings in .env
The error is saying that the username is ‘root’ and that the password is ‘root’ and that the database is ‘p4’ on your production server. Are these credentials correct?

**Comment by cpowell1** [comment]
Well I just went through and deleted the files and retried the process, and that seemed to fix the errors... so it must have been something small I was missing! Thanks for your help!
