### ISSUE TITLE
Question about public function "tags()"

### ISSUE THREAD

**Issue by ningchen8743** [susanBuck/dwa15-fall2018#125]
On db-many-to-many.md, a public function "tags()" is added to the class "Book".
In the section "Query relationship example", however, it appears "tags" is used as if it is a variable (array)
rather than a function:
foreach ($book->tags as $tag) {
	dump($tag->name);
}

Does Laraval somehow dynamically add the class member "tags" which happens to have the same name with the "tags()" function?

Please point out if you have some thoughts, thank you all!

**Comment by jessupjs** [comment]
Hi Ning!

I just happen to be on, and curious because I've struggled with the same question about Eloquent relations.

The difference between pointing to a field `$tag->name` and a function`$tag->name()` seems to be in the data it returns (here in corresponding context to my project):

```
// Many-to-Many
        dump($team->users);
        dump($team->users());
        die();
```
```
Collection {#414 ▼
  #items: array:2 [▼
    0 => User {#513 ▶}
    1 => User {#514 ▶}
  ]
}
```
```
BelongsToMany {#521 ▼
  #table: "team_user"
  #foreignPivotKey: "team_id"
  #relatedPivotKey: "user_id"
  #parentKey: "id"
  #relatedKey: "id"
  #relationName: "users"
  #pivotColumns: array:2 [▶]
  #pivotWheres: []
  #pivotWhereIns: []
  #pivotValues: []
  +withTimestamps: true
  #pivotCreatedAt: null
  #pivotUpdatedAt: null
  #using: null
  #accessor: "pivot"
  #query: Builder {#516 ▶}
  #parent: Team {#480 ▼
    #connection: "mysql"
    #table: "teams"
    #primaryKey: "id"
    #keyType: "int"
    +incrementing: true
    #with: []
    #withCount: []
    #perPage: 15
    +exists: true
    +wasRecentlyCreated: false
    #attributes: array:7 [▶]
    #original: array:7 [▶]
    #changes: []
    #casts: []
    #dates: []
    #dateFormat: null
    #appends: []
    #dispatchesEvents: []
    #observables: []
    #relations: array:1 [▼
      "users" => Collection {#414 ▼
        #items: array:2 [▼
          0 => User {#513 ▶}
          1 => User {#514 ▶}
        ]
      }
    ]
    #touches: []
    +timestamps: true
    #hidden: []
    #visible: []
    #fillable: []
    #guarded: array:1 [▶]
  }
  #related: User {#407 ▶}
}
```
Notice the `#relationName: "users"` in the `BelongsToMany` return matches the field `users` that yielded the Collection, and I believe that's because Eloquent is using `__construct` magic to assign that property.  In vendors, check out ** \Illuminate\Database\Eloquent\Relations\BelongsToMany ** to have a closer look.  Here's the relevant part that I've found:

```
/**
     * Create a new belongs to many relationship instance.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  \Illuminate\Database\Eloquent\Model  $parent
     * @param  string  $table
     * @param  string  $foreignPivotKey
     * @param  string  $relatedPivotKey
     * @param  string  $parentKey
     * @param  string  $relatedKey
     * @param  string  $relationName
     * @return void
     */
    public function __construct(Builder $query, Model $parent, $table, $foreignPivotKey,
                                $relatedPivotKey, $parentKey, $relatedKey, $relationName = null)
    {
        $this->table = $table;
        $this->parentKey = $parentKey;
        $this->relatedKey = $relatedKey;
        $this->relationName = $relationName;
        $this->relatedPivotKey = $relatedPivotKey;
        $this->foreignPivotKey = $foreignPivotKey;

        parent::__construct($query, $parent);
    }
```

Good luck!

**Comment by susanBuck** [comment]
This is called a dynamic property. 

First addressed here: https://github.com/susanBuck/dwa15-fall2018/blob/b552298cde7fcc6aa4c07de16f6deedc1a525e53/laravel/db-one-to-many.md#read-querying-with-relationships

And you can read more here: [Eloquent: Relationship Methods Vs. Dynamic Properties](https://laravel.com/docs/5.7/eloquent-relationships#relationship-methods-vs-dynamic-properties)

**Comment by susanBuck** [comment]
Closing this issue to keep the forum cleaned up during the project deadline rush, but feel free to ask any follow-up questions or start a new thread!
