### ISSUE TITLE
403 error with phpmyadmin

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#127]
I've been using Heidisql because I get a 403 error (access forbidden) for phpmyadmin through localhost (below). I s there any way I can fix this? The XAMPP welcome page works fine through local host except I can't click into phpmyadmin.

![image](https://user-images.githubusercontent.com/43080775/50049333-3d598880-00b1-11e9-8fc5-b0ec304e03a4.png)

**Comment by Sud-B** [comment]
Thank you! I had a look, where is this folder located? I looked under XAMPP but don't see it.

**Comment by Sud-B** [comment]
Is it under mysql/data? Which file?

**Comment by susanBuck** [comment]
If you don't see it at `C:\xampp\phpMyAdmin` it may be why you're unable to load it in the browser.

I'm not sure why it wouldn't be there.

You may need to re-install XAMPP. If you do, before doing so, you should make a copy of your htdocs folder, as well as the files referenced in the notes on [local domain](https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/local-domain.md).

**Comment by Sud-B** [comment]
Thanks Susan.  I was halfway through re-installing XAMPP when I got your message.  I'd made a copy of  htdocs but hadn't done anything about the other files. The new install has a phpmyadmin folder and it works now (this is much better than Heidisql). Should I just follow through the "local domain" instructions from scratch? The production server has got all the virtual host information. I'm assuming I need to mirrir it?

**Comment by susanBuck** [comment]
Hi @Sud-B - Glad the re-install did the trick for phpmyadmin, and you did the copy of `htdocs` as that's the most important part.

I would just go through the local domain instructions from scratch - it shouldn't take too long to bring things back up to working order. 

I'd do it by following the notes, not trying to mirror the stuff on production - just because the paths on production are different.

**Comment by Sud-B** [comment]
Thank you Susan. Yes it does seem a lot simpler to go through the local domain instructions, I'm glad I don't have to mirror the production server. Hopefully nothing else comes up :)
