### ISSUE TITLE
Constant refresh

### ISSUE THREAD

**Issue by mihika-shilpi** [susanBuck/dwa15-fall2018#128]
If I have a table of rows with an 'upvote' feature, and the table is organised by number of votes, is there a way to make the rows automatically shift when a user 'upvotes' an item without a page refresh?

**Comment by DoryAzar** [comment]
You will need javascript for that.
That is the main different between client side languages (like javascript) and server side languages (like php).

**Comment by susanBuck** [comment]
@DoryAzar Is correct. 
Not only would you use JS to re-arrange the rows in the table, you'd also use it to send an Ajax request to the server letting it know which row should be updated with the upvote.

Closing this thread out, but feel free to ask any follow-up questions!
