### ISSUE TITLE
lamp ip address does not work

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#13]
Hi,

When I tried to open lamp ip address I got following message: Please log into your Droplet with SSH to configure the LAMP installation.

Do I need to do this? I selected lamp 18.04 as 16.04 was not there. Also my document root does not have any php files.

Thanks

**Comment by DoryAzar** [comment]
That message is correct. This is the default HTML page. If you continue the lecture, you will know what to do next. I also used 18.04 (seems to be the latest one available) and you are right, there is no info.php that comes in the folder, only index.html.

**Comment by hemantbajpai** [comment]
Thanks

**Comment by susanBuck** [comment]
Looks like they've updated to 18.04 since last Wed (when I recorded that lecture). 

FYI - Either version will work.
