### ISSUE TITLE
(XAMPP) Unknown Database

### ISSUE THREAD

**Issue by dnoren32** [susanBuck/dwa15-fall2018#130]
I'm on a PC and am getting this error when trying to set up a migration. 

```
 Illuminate\Database\QueryException  : SQLSTATE[HY000] [1049] Unknown database 'p4' (SQL: select * from information_schema.tables where table_schema = p4 and table_name = migrations)

  at C:\xampp\htdocs\p4\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [1049] Unknown database 'p4'")
      C:\xampp\htdocs\p4\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:70

  2   PDO::__construct("mysql:host=localhost;port=3306;dbname=p4", "root", "", [])
      C:\xampp\htdocs\p4\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:70

  Please use the argument -v to see more details.
```

I feel like it could be related to this [issue ](https://github.com/susanBuck/dwa15-fall2018/issues/105). Though I fixed the production server, the local side of things is still giving me an error similar to the one above.

`"Database connection test" => "FAILED: SQLSTATE[HY000] [1049] Unknown database 'p4' (SQL: SHOW DATABASES;)"`

**Comment by susanBuck** [comment]
Can you share the full output of a [debug route](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/db-local-config.md#test-your-connection) ? When you do, uncomment the line `$debug['MySQL connection config'] = config('database.connections.mysql');` so we can see those details as well.

**Comment by susanBuck** [comment]
Based on a Slack chat with @dnoren32 I believe this issue is no longer relevant, so I'm closing this thread. 

Feel free to re-open if necessary.
