### ISSUE TITLE
Issue Retrieving Date from Input Form

### ISSUE THREAD

**Issue by chantalthomas** [susanBuck/dwa15-fall2018#131]
Hello!

I am having an issue with input type of date in one of my forms. I have tried various ways to format my date but date is still null when I dump start_date or end_date. The date should not be null since I am selecting a date from the date picker. Are there any special date formats that I need to be considering in order to retrieve dates from the request?

Thanks in advance!

**Comment by chantalthomas** [comment]
Just as an example, I have tried reformatting my dates with the code below:

```php
public function store(Request $request)
    {
        $startDate = $request->start_date;
        $phpStartDate = date('Y-m-d', strtotime($startDate));
        $endDate = $request->start_date;
        $phpEndDate = date('Y-m-d', strtotime($endDate));


        $event = new Event();
        $event->title = $request->title;
        $event->description = $request->description;
        $event->start_date = $phpStartDate;
        $event->end_date = $phpEndDate;

        //dd($request->start_date);


        $event->save();


        return redirect('/user-profile');
    }```

Which doesn't return a null date but sets them equal to 1970-01-01. Which is invalid.

**Comment by susanBuck** [comment]
To debug this I'd break down this line:
```
$phpStartDate = date('Y-m-d', strtotime($startDate));
```

E.g. a couple dump statements to see what the individual values are:
```
dump($startDate);
dump(strtotime($startDate))
```
What values does that show?
