### ISSUE TITLE
Seeder issue "Class CategoriesTableSeeder does not exist"

### ISSUE THREAD

**Issue by pingji00** [susanBuck/dwa15-fall2018#132]
I ran into an issue when I do 

php artisan migrate:fresh --seed

It was fine when there's only one table/tableSeeder, but it failed when there're two tables. 

I've already add both of the seeder file into DatabaseSeeder.php

Here's error info

/Applications/MAMP/htdocs/p4 (master) ! $ php artisan migrate:fresh --seed
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_11_19_153116_create_foods_table
Migrated:  2018_11_19_153116_create_foods_table
Migrating: 2018_12_18_213657_create_categories_table
Migrated:  2018_12_18_213657_create_categories_table
Seeding: FoodsTableSeeder
Seeding: CategoriesTableSeeder

   ReflectionException  : Class CategoriesTableSeeder does not exist

  at /Applications/MAMP/htdocs/p4/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
    775|         if ($concrete instanceof Closure) {
    776|             return $concrete($this, $this->getLastParameterOverride());
    777|         }
    778| 
  > 779|         $reflector = new ReflectionClass($concrete);
    780| 
    781|         // If the type is not instantiable, the developer is attempting to resolve
    782|         // an abstract type such as an Interface of Abstract Class and there is
    783|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   ReflectionClass::__construct("CategoriesTableSeeder")
      /Applications/MAMP/htdocs/p4/vendor/laravel/framework/src/Illuminate/Container/Container.php:779

  2   Illuminate\Container\Container::build("CategoriesTableSeeder")
      /Applications/MAMP/htdocs/p4/vendor/laravel/framework/src/Illuminate/Container/Container.php:658

  Please use the argument -v to see more details.

**Comment by susanBuck** [comment]
Did you create the new seeder with artisan, or manually create it?

If the latter, the new seed class file might not be in composer's autoloading map. 

Ref: [Production database setup > Troubleshooting > Error: Class BooksTableSeeder does not exist](https://github.com/susanBuck/dwa15-fall2018/blob/b622bd78e93562ced577216cbcd84623eec0fe87/laravel/db-production.md#error-class-bookstableseeder-does-not-exist)

**Comment by pingji00** [comment]
"composer dump-autoload” Works!!

Thank you, Susan!

**Comment by susanBuck** [comment]
Excellent! Glad that did the trick.
