### ISSUE TITLE
Production domain view is blank

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#134]
I have both local and production domains set to p4/public and can view my welcome page in local but not in the production domain (just get a blank page - no error message or activity)

**Comment by Sud-B** [comment]
I have both local and production domains set to p4/public and can view my welcome page in local but not in the production domain (just get a blank page - no error message or activity)

**Comment by susanBuck** [comment]
Can you confirm you've double checked the 3 common issues listed at the bottom of this [note set](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/deploy-to-digital-ocean.md#troubleshooting)?

**Comment by Sud-B** [comment]
I re-checked now. Here is a screen shot. I can see env and vendor files. For the permissions, I get the message "No such file or directory" in CMDER

![image](https://user-images.githubusercontent.com/43080775/50242398-2c9e6080-0398-11e9-9c01-789a1828b024.png)

**Comment by pausman** [comment]
you need to copy .env.example to .env on production and then make the changes needed to it under the database and app sections.

**Comment by Sud-B** [comment]
Thanks. I just tried copying .env.example to env in production but get a message " No such file or directory". Should it be in a specific directory?

**Comment by Sud-B** [comment]
Thanks Dory. I'll go through again.

**Comment by Sud-B** [comment]
It works! Thank you :)
