### ISSUE TITLE
Routes Not Working in Production

### ISSUE THREAD

**Issue by T-Waddell** [susanBuck/dwa15-fall2018#138]
I understand if this is too late for the assignment, but I would like to know where I went wrong. My routes are working fine on my local server, but in production only my home page is working. All other routes result in a 500 error. This wasn't the case during my testing in production after creating my CRUD functionality, so it seems like I made an error somewhere when building my pivot table. Any advice would be appreciated.

**Comment by susanBuck** [comment]
Echo'ing @DoryAzar's suggestion.
If that doesn't solve it, check your Laravel error log on production for more clues.

**Comment by T-Waddell** [comment]
My .env file was correct, but I forgot to run the migration for a new table in production. It seems to be working now. Thank you both!
