### ISSUE TITLE
Possible error in the path in the <img> tag

### ISSUE THREAD

**Issue by venkateshmantha** [susanBuck/dwa15-fall2018#14]
Hi,

Shouldn't the src path in the <img> tag instead be `src='images/kitten.jpg'` considering the path inside the html tags is relative?

`<h1>Hello World!</h1>`
`<img src='/images/kitten.jpeg' alt='Adorable kitten'>`

**Comment by susanBuck** [comment]
You can use absolute or relative URLs. 
The forward slash is an absolute URL, and it will work fine assuming the project you're working on has its document root set appropriately.

**Comment by susanBuck** [comment]
@ccrane I also prefer absolute URLs as they're more explicit.

This is in contrast to what I did for the image in [hello-world/index.php](https://github.com/susanBuck/hello-world/blob/43bba5c99db655be5faf99c0697a02888089f0f9/index.php#L16), but that was not on purpose - just wasn't tending carefully to the path I was using.
