### ISSUE TITLE
Reading assignments

### ISSUE THREAD

**Issue by fpizzuta** [susanBuck/dwa15-fall2018#17]
How can I see the reading assignments without having to take the quiz again?

**Comment by pausman** [comment]
You can "take" assignment/quiz but not submit it.

Pat

**Comment by susanBuck** [comment]
Please don't post about course logistics here - as noted in Week 1 and the policies on the Issues forum, I prefer to keep the content here about troubleshooting, curriculum, etc.

Please see: https://dwa15.com/issues-forum#Posting%20policies
