### ISSUE TITLE
[redacted] (off-topic)

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#18]
Hi,

Where do we need to provide url for git repository for project? Do we need to send email for submission?
I could not find any place to provide url in course website.

Thanks

**Comment by susanBuck** [comment]
Please don't post about course logistics here - as noted in Week 1 and the policies on the Issues forum, I prefer to keep the content here about troubleshooting, curriculum, etc.

Please see: https://dwa15.com/issues-forum#Posting%20policies
