### ISSUE TITLE
where do php files go?

### ISSUE THREAD

**Issue by pausman** [susanBuck/dwa15-fall2018#19]
Is there a standard for external php files (include/required) storage? In a subdirectory? At top level?
Thanks
Pat

**Comment by DoryAzar** [comment]
Pat -
There sure is a need to structure files...different people/orgs do it in different ways...
This is what I did for this first project, @susanBuck will most likely direct us later in the course on how best to do it :
- root: html files
- styles folder: I put in the css 
- scripts folders: for javascript if you have any
- controllers folder: for logic php
- assets folder: for pictures

Hope this helps.
