### ISSUE TITLE
Intermittent 404

### ISSUE THREAD

**Issue by venkateshmantha** [susanBuck/dwa15-fall2018#22]
Hi,

Anyone else experiencing 404 not found intermittently? I can confirm that my sub-domain on production was up and running but it keeps failing with 404 sometimes. Could this be an issue on the Namecheap servers?

Here is the url for reference: http://p1.venkateshmantha.me but cannot guarantee if the problem can be replicated due to the nature of it.

Thanks

**Comment by susanBuck** [comment]
Haven't noticed this on my subdomain tests, and `http://p1.venkateshmantha.me/` is working on my end (currently).

I'll make a note to be on the lookout for this when grading your P1, as you shouldn't be penalized for a intermittent server issue beyond your control (assuming you've done your due diligence, which you have by making this post).

Curious if anyone else is experiencing this...

**Comment by susanBuck** [comment]
Follow-up question @venkateshmantha - does it ever happen with your primary domain, or is it always just the subdomain?

**Comment by venkateshmantha** [comment]
@susanBuck noticed it to happen only with the subdomain.

**Comment by venkateshmantha** [comment]
Upon further inspection, I had a URL redirect record set which I did not delete in Namecheap's DNS settings which I believe could be the cause of the problem, because the issue sometimes occurred when I tried to visit the domain from a different website(Github, mobile browser) instead of manually typing the url in the browser.
I am not sure if that was causing the issue definitively but deleting the record seems to have solved the problem for now.

**Comment by susanBuck** [comment]
@venkateshmantha Glad you sorted it out.
