### ISSUE TITLE
Error log Week 1 assignment

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#23]
I'm a little late and stuck on this 1 question.  I'm using windows then gone into CMDER.  The file I'm trying to access I think is called error in XAMPP\Apache\logs and I've gone into this directory using the cd command but when I try the CAT command (Or more command), I can't get the file to display. I've copied from CMDER below. Any ideas on what else I need to do? And thank you enormously :)

C:\xampp\apache\logs
λ cat error
cat: error: No such file or directory

C:\xampp\apache\logs
λ more error
Cannot access file C:\xampp\apache\logs\error

**Comment by mdeforest** [comment]
is it possibly called `error.log` and not just `error`?

**Comment by Sud-B** [comment]
Thank you ! That worked :)

**Comment by Sud-B** [comment]
I guess I'll close the issue now. Have a very good evening!!
