### ISSUE TITLE
Difficulty cloning - C:/Program Files/OpenSSH/ssh.exe: No such file or directory fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by dickblair** [susanBuck/dwa15-fall2018#24]
I am having difficulty cloning my repository.  I have verified it is public.  I have also verified my ssh connection works as you can see in the logs below.  However, the problem looks related to SSH.  I have tried deleting my SSH keys and my repository and starting over from the beginning.  Any idea what the issue could be.

D:\XAMPP\htdocs
λ ssh -T git@github.com
Hi dickblair! You've successfully authenticated, but GitHub does not provide shell access.

D:\XAMPP\htdocs
λ git clone git@github.com:dickblair/hello-world.git
Cloning into 'hello-world'...
'C:/Program Files/OpenSSH/ssh.exe': C:/Program Files/OpenSSH/ssh.exe: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by DoryAzar** [comment]
Make sure you are using the correct SSH cloning address. You can find it by clicking on the “clone” button on the top right of the repository page. There is a link inside the pop up that says “use ssh”. Make sure you use that address. 

The address should be in the form : https://github.com/USERNAME/Repositoryname.git

**Comment by mdeforest** [comment]
I don't think its an issue with the cloning address. The address looks correct. I am not running on windows, but I did some research and came across this StackOverflow post: https://stackoverflow.com/questions/2499331/git-with-ssh-on-windows/8713121#8713121 The problem seems to be similar to the one mentioned in this post.

**Comment by DoryAzar** [comment]
The address is wrong. We should be using the ssh and not the svn address. Try it out it should work just fine.

**Comment by mdeforest** [comment]
I think that the ssh address should begin with `git@github`. `https://` would refer to the https protocol.

**Comment by susanBuck** [comment]
@dickblair I just tested `git clone git@github.com:dickblair/hello-world.git` and was able to successfully clone your hello-world git repo - so you've got the command/path correct.

Given that, I'd focus on the error `'C:/Program Files/OpenSSH/ssh.exe: No such file or directory`. I'm doing some research on that now and will follow-up with what I find.

**Comment by dickblair** [comment]
@susanBuck 
the output of which ssh is
/usr/bin/ssh

I do have OpenSSH, but it is a service on my WIN10 box, not an executable.  Git has an executable.  I feel like I need to let Cmder know I need to use C:\Program Files\Git\usr\bin\ssh.exe but not sure how to do configure that.  Did I miss a step?

**Comment by dickblair** [comment]
@mdeforest when I type that command it says export is not recognized as an internal or external command.  I added it manually through the windows environmental variables, but that did not work.  I also set GIT_SSH=C:\Program Files\Git\usr\bin\ssh.exe but I still get 

`Cloning into 'hello-world'...
'C:/Program Files/OpenSSH/ssh.exe': C:/Program Files/OpenSSH/ssh.exe: No such file or directory
fatal: Could not read from remote repository.`

**Comment by dickblair** [comment]
@mdeforest @susanBuck Ok I found something interesting.  When I type 
`where ssh` in Gitbash I get 
`C:\Program Files (x86)\Git\usr\bin\ssh.exe`

but when I type `where ssh` in Cmder I get
`C:\Windows\System32\OpenSSH\ssh.exe`
`C:\Program Files (x86)\Git\usr\bin\ssh.exe`

**Comment by dickblair** [comment]
@mdeforest I get the same error running git clone in Gitbash, still looking for the OpenSSH executable

**Comment by mdeforest** [comment]
Oh yeah probably because it doesn't necessarily mean thats what Git is using..ok I will keep researching

**Comment by susanBuck** [comment]
@dickblair To compare and contrast, here's what I see on my Windows machine:

```
λ where ssh
C:\Windows\System32\OpenSSH\ssh.exe
C:\Program Files\Git\usr\bin\ssh.exe
```

```
λ which ssh
/c/WINDOWS/System32/OpenSSH/ssh
```

Also, it sounds like you already know how to do this (you mentioned environment variables above), but for reference for you/anyone else reading this thread, [here are supplemental notes I have on editing your PATH environment variable](https://github.com/susanBuck/dwa15-fall2018/blob/master/command-line/path.md) to control what programs are executed when commands are run.

**Comment by dickblair** [comment]
@susanBuck @mdeforest Sorry guys I gave up on doing this the right way and I hacked it as I already spent about 50 hours on it.  I copied OpenSSH folders with executables to where git said they were missing.  I would have rather figured out what was pointing to the wrong location, but at this point I don't feel confident I can do it in a timely manner.

**Comment by DoryAzar** [comment]
This is itching me I must say... I read both @susanBuck and @mdeforest suggested articles. Your defined paths seem OK. They seem similar to what @susanBuck has on her machine. I don’t know if you tried to do `which ssh` as suggested so that we see which ssh is being used by Cmdr.

I do have a theory...I can’t validate it though unless you try. If the which command is giving you the path to the right ssh then i believe that there has been a conflict in the generation of your keys. The keys might have been generated with Openssh and now they are being read with the git ssh.Now that your env variables are set correctly and if the which is definitely using the git ssh, I would suggest that you recreate your keys using the correct git ssh-keygen. It is a theory... but i think it is worth trying once you submit your project.

**Comment by susanBuck** [comment]
@dickblair Understood. Sorry to hear your churned 50 hours on it - that's a lot! 
I think your solution is reasonable/resourceful. 

@DoryAzar Promising theory! I'd be curious to hear the results, but like you said, maybe not something worth dealing with until post project deadline and @dickblair has had a break from this particular issue. : )

**Comment by susanBuck** [comment]
Closing this issue now since I believe @dickblair came to a resolution, but feel free to make a new thread if anything is still pending.
