### ISSUE TITLE
Nu HTML Checker Errors

### ISSUE THREAD

**Issue by jpersson74** [susanBuck/dwa15-fall2018#25]
Hello - 
When running my html through the Nu HTML Checker I get the error below twice from my php blocks. Logic is in a separate file and the errors are happening on the <?php require line and then again when I add the quote to the page later on in the html. Is this something to be concerned about?

Error: Saw <?. Probable cause: Attempt to use an XML processing instruction in HTML. (XML processing instructions are not supported in HTML.)

**Comment by DoryAzar** [comment]
What did you name your file? make sure you name it .php not .html

**Comment by susanBuck** [comment]
@jpersson74 Check out this post - https://github.com/susanBuck/dwa15-fall2018/issues/15

The validator is for HTML code only. Make sure you're not trying to validate PHP code directly from your code editor.

**Comment by q0w9e8r7t6y5** [comment]
I had this same error. Basically we have to view the page from the local server, view source, and then copy/paste that into the validator.

**Comment by jpersson74** [comment]
Thanks for the replies, everyone. I was able to get a clean scan of just the html.
