### ISSUE TITLE
SSH into DigitalOcean giving 'permission denied' message

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#28]
I successfully got the public key again using the cat command, and added the SSH key in Digital Ocean, then created a Droplet with the SSH key but when I use the ssh root@ip-address, I get the message "Permission denied (publickey)."

I've tried finding answers online but they either didn't explain why they were instructing you to use certain commands or didn't seem to resolve the issue. Any suggestions?

In case this is relevant, if I go to remove and re-add the SSH key, I can't see the one I've created. But if I try to just add a new one with the same key, it says it already exists; and if I create another Droplet, I still have the option to select that SSH key.

**Comment by DoryAzar** [comment]
Any chance you can show the full error message? Are you by any chance on MAC Sierra?

**Comment by baugh20s** [comment]
Sorry, yes I'm on a MacBook Air with Sierra. Screenshot attached!
![screen shot 2018-09-19 at 1 37 53 pm](https://user-images.githubusercontent.com/20144373/45770751-41405080-bc11-11e8-8d1e-e72be6742361.png)

**Comment by baugh20s** [comment]
It says 'sarahbaughman'

![screen shot 2018-09-19 at 6 30 24 pm](https://user-images.githubusercontent.com/20144373/45785433-54b3e180-bc3a-11e8-9132-412e13493462.png)

**Comment by DoryAzar** [comment]
@baugh20s Love these permission conflicts.

- Are you the admin on this machine?
could you tell us what you see when you type whoami in the ~/.ssh folder?
- is ssh -T git@github.com working?
- Did you give a name other than the default id_rsa to your keys?
- Did you add the IdentityFile to the config file?

**Comment by DoryAzar** [comment]
Ok I see something unusual here. dwa and dwa.pub don’t see to be in ~/.ssh
could you do `ls ~/.ssh`?

**Comment by baugh20s** [comment]
![screen shot 2018-09-19 at 8 04 09 pm](https://user-images.githubusercontent.com/20144373/45788231-3e605280-bc47-11e8-9cfb-b86cebbe9300.png)

**Comment by baugh20s** [comment]
I just removed the one that appears to be in my home directory, but left the one that's in the ssh directory; still getting the same access denied message

**Comment by DoryAzar** [comment]
Alright lets take a step back:
- Is your droplet on? so if you go to your ipaddress in the browser, you see the index file?
- If it’s on then let’s try 2 things:
1) `chown -R sarahbaughman ~/.ssh` this changes the ownership of this ssh folder 
2) `chmod -R 600 ~/.ssh` this changes the permissions of all files to make them not writable

let s try again. If these don’t lead anywhere then I have one more thing to suggest

**Comment by baugh20s** [comment]
I don't see the index file - it tells me to log into my droplet with SSH

![screen shot 2018-09-19 at 8 30 22 pm](https://user-images.githubusercontent.com/20144373/45788860-f17e7b00-bc4a-11e8-92bc-b6d9f9e10600.png)

**Comment by DoryAzar** [comment]
yes that is correct this is the default index file that DO has.

Wanna try the chown and chmod. If it gives an error after you execute them just add `sudo` before each command rerun them

**Comment by baugh20s** [comment]
Ah okay. I tried those, except I think 600 made it not executable, so I did 700.

![screen shot 2018-09-19 at 8 42 50 pm](https://user-images.githubusercontent.com/20144373/45789250-acf3df00-bc4c-11e8-89de-9d8cd0dbead8.png)

**Comment by susanBuck** [comment]
@baugh20s 
Can you read through these supplemental notes:
[Permission denied (publickey) when SSH'ing into DigitalOcean server](https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/permission-denied-public-key.md)

These were referenced at the end of the [Deploy to production](https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/deploy-to-production.md) notes, but I just realized it was a broken link so it's possible you tried to read them but they didn't load?

**Comment by susanBuck** [comment]
Follow-up - those notes say:

> If you've just created the Droplet, the quickest way to resolve this problem is just to destroy the droplet and create a new one.

I suggest going that route.

Before doing that though, go into your DigitalOcean settings double check your public key.

Then, create a new Droplet, triple checking that you check the box to include that SSH key.

**Comment by DoryAzar** [comment]
since no change then this isnt the issue. 600 or 644 seems to be the most appropriate. so dont be afraid to set them all to 600 or 644.

Now here is the last thing that comes to my mind. If you do: `nano ~/known_hosts`. you will see all the hosts that were given permission. 
- Delete the line that has the your ip in it.
This will trigger the system to ask you again for permission to add it.
- so now when u do ssh root@ip it is going to ask you the yes and no question :). please take a screen shot of that question and type “yes” and tell us the outcome

**Comment by baugh20s** [comment]
Did that; here's the screenshot. I'm going to try destroying and recreating the droplet!

![screen shot 2018-09-19 at 9 08 45 pm](https://user-images.githubusercontent.com/20144373/45789964-8fc10f80-bc50-11e8-8029-a3d75576a2be.png)
