### ISSUE TITLE
mySQL Expectations?

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#3]
Good afternoon!

I gathered from your recording and the Project summary notes that in later projects we will be using the Laravel framework to connect to a database.  Will we be using mySQL for database work?  If so, will we be learning some about the language in this course or should I devote some time to becoming familiar with it on my own?

Many thanks!
j

**Comment by susanBuck** [comment]
Hi @jessupjs - Yes, MySQL is the database technology we'll be using. 

We will touch briefly on SQL, the language that powers MySQL. I will provide an overview, and assign some readings. 

Ultimately, though, we'll be using functionality within Laravel (the framework we'll use later in the semester) that abstracts SQL, and we'll focus our attention on this abstraction.

**Comment by jessupjs** [comment]
Thanks @susanBuck!  

Out of curiosity, will we become familiar with any of its syntax or some basic scripts?  Or is most of that handled by Laravel?

Tks again!
j

**Comment by susanBuck** [comment]
Yes, you'll see some basic syntax/scripts, but you won't be expected to write any SQL.

Even though we use the tools Laravel provides to communicate with the database (abstracting SQL in the process), it's still useful to understand a little bit about what's happening "behind the scenes" in order a) troubleshoot more effectively and b) have a deeper understanding of what the framework tools are actually doing.
