### ISSUE TITLE
Bootstrap, SASS

### ISSUE THREAD

**Issue by rdudeney** [susanBuck/dwa15-fall2018#30]
Where can one find CSS tools like Bootstrap, SASS? How do you decide which is best to add to your web-page?

**Comment by DoryAzar** [comment]
Bootstrap is quite a decent framework. It’s widespread, has great documentation and has multiple ways of integrating with your application. So if you do have an intention to use a framework, you should probably use one that has good documentation like Bootstrap. 

Here is the website: <http://getbootstrap.com>
