### ISSUE TITLE
PHP error reporting on XAMPP

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#31]
While updating for error reporting in PHP, I go to the location C:\xampp\php\php.ini but find 2 versions: production and development. Do we update both? Default seems to be:
display_errors
;   Default Value: On
;   Development Value: On
;   Production Value: Off

; display_startup_errors
;   Default Value: Off
;   Development Value: On
;   Production Value: Off

; error_reporting
;   Default Value: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
;   Development Value: E_ALL
;   Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT

**Comment by DoryAzar** [comment]
Since this is on your local machine and we are not creating a distinction between development and production on our local machines (remember that we are using DO with LAMP for production) then I would suggest using the default.

**Comment by DoryAzar** [comment]
I hear you. There should be just one php.ini (that would be the default one). You probably want to make changes to that one.

**Comment by Sud-B** [comment]
Thanks Dory. There seem to be 2 by default. They both seem to have the right error reporting so I'll leave them as they are for now. Appreciate your help :)
