### ISSUE TITLE
Cloning GIT repositary through CMDER

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#32]
I’m trying to clone my GIT repository to my local server through CMDER but get this error message: 

```
"Permission denied {Public key}. Could not read from remote repository. Please make sure you have correct access rights and the repository exists". 
```

I've followed the lecture instructions and copied the SSH link over. Any suggestions. Thanks,

**Comment by mdeforest** [comment]
Does running `ssh -T git@github.com` work?

**Comment by susanBuck** [comment]
+1 to @mdeforest's question.
Also, what is the SSH link you're trying? We can test on our computers to see if we can reproduce the issue.

(Side note, I edited your post to add Markdown syntax to make the error message easier to parse [reference](https://github.com/susanBuck/dwa15-fall2018/issues/1)).

**Comment by Sud-B** [comment]
Thanks Michaela/Susan.  I think I'd omitted a step. I'm trying by going though the process with the lecture video/notes from the beginning. So far I've got "Bad owner or permissions on C:\\Users\\s999b/.ssh/config" twice at the test stage. Third time it will work hopefully :)

**Comment by susanBuck** [comment]
If you're still running into the `bad owner or permissions` error on the ssh config file, see this post: #12 

There are options there to either circumvent or address that particular error.

**Comment by Sud-B** [comment]
Thank you Susan. Finally success. Your video at the end of the stream for post 12 and going into the properties for config then reducing the users to 3 is what worked.
