### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/dwa15-fall2018#33]
When I tried to validate my url, I got the following unexpected response when trying to retrieve <http://p1.vanillacandy.website/>

404 Not Found

I am able to see the website on browser.

**Comment by mdeforest** [comment]
I am not getting a 404 response when validating the HTML. Are you still receiving that response or has it been resolved?

**Comment by DoryAzar** [comment]
Same here. I see it alright and the validator has done the check <https://validator.w3.org/nu/?doc=http%3A%2F%2Fp1.vanillacandy.website>

**Comment by vanillacandy** [comment]
Thank you for the responses. From my end, I kept getting 404 response on validation website. When I tested my url on browser, it's very unstable. Sometimes my webpage shows up, sometimes it doesn't without me changing any configuration.

**Comment by mdeforest** [comment]
Could it be similar to this issue? #22

**Comment by vanillacandy** [comment]
Thank you @mdeforest , that solved my problem.
