### ISSUE TITLE
Syntax clarification: require('file.php') vs. require 'file.php'

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2018#35]
In the course notes on imports, I note that the syntax for requiring a file looks like this:

```php
require 'helpers.php';
```

However, I've noticed myself sometimes writing it as the following, both in lecture videos and some examples:
```php
require('helpers.php');
```

Because of this inconsistency, I wanted to clarify -

**While both styles will work, the first style (no parenthesis) is most accurate.** 
Require is technically not a function, but a language construct/statement.

Sorry for any confusion this may have caused! As you'll see when we get into the framework portion of the semester, we'll move away from using require statements in favor of something called autoloading. Because this is something I use more frequently in my day-to-day work, I always mix-up whether parenthesis should/shouldn't be included when requiring. 

I've just updated foobooks0 and other examples to remove instances of require with parenthesis.

**Comment by jessupjs** [comment]
Thanks!

 Should we revise our projects at this point if parentheses were used?  Also is the `;` necessary inside of the angle brackets?

**Comment by susanBuck** [comment]
@jessupjs - Good question - no need to revise your projects. Either approach is acceptable.

Can you clarify/give an example of what you mean by `;` instead of angle brackets?

**Comment by jessupjs** [comment]
@susanBuck I'm sorry, and thanks for the feedback.  For example:
`<?php require('p1PHP/rq_logic.php'); ?>`

I wasn't sure if the semi-colon was required or best-practice.  Or perhaps omitting it has an unexpected consequence similar to closing the "rq_logic.php" file with a `?>` which you warned against.

**Comment by susanBuck** [comment]
Another good Q - 

When you have a single PHP statement in a block of php code (`<?php ... ?>`), the `;` is optional since the end of that statement is implied by the closing PHP tag.

It won't create any unexpected technical consequences.

I can only think of a potential "human error" consequence, which is if you later go to add another statement, you might forget that you need to add the `;` on the previous statement.

I couldn't find anything in the PSR style guidelines about this, so I say go with what you prefer. I know I'm guilty of writing it with and without.
