### ISSUE TITLE
127.0.0.1 - No longer working

### ISSUE THREAD

**Issue by cordovas** [susanBuck/dwa15-fall2018#36]
I'm just curious to know why 127.0.0.1 is no longer working. Isn't the host file just directing the domain names to this local ip?

**Comment by DoryAzar** [comment]
It should be working. If it is not that means even `localhost` shouldn’t be working for you.

**Comment by ccrane** [comment]
@cordovas I'm not sure if you are using MacOS or Windows. Could you share your host file contents?

**Comment by baugh20s** [comment]
Is it not working for the previous projects as well? I'm guessing this isn't the issue here but I had a typo in the IP address when I created the new host for foobooks0, so my hello-world-dwa was still working but foobooks0 wasn't. 

What message are you seeing and at what point?

**Comment by susanBuck** [comment]
`127.0.0.1` is just a loopback address to `localhost`, and once we started using vhosts, `localhost` no longer functions as expected. You can read more about this/fix this by following these notes:

[Local domain: Fixing http://localhost](https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/local-domain.md#fixing-httplocalhost)

**Comment by fpizzuta** [comment]
I think once we start doing host header authentication with vhosts apache no longer knows where localhost points to in the directory structure.
