### ISSUE TITLE
PhpStorm - File not found: git.exe

### ISSUE THREAD

**Issue by rdudeney** [susanBuck/dwa15-fall2018#39]
After installing PhpStorm on my computer, I continue to get the following error message on the editing page:

```
Cannot Run Git
File not found: git.exe
```

I assume Phpstorm wants to connect to Github, but I don't want it to. Is there a way for me to turn off this message?

**Comment by hemantbajpai** [comment]
Where and when do you see this error? Normally when I add new file in project it asks me if I want to add it in git and I say no as we do not want to use git through phpstorm.

**Comment by jpersson74** [comment]
I was also getting the same message. I ended up pointing the path to git.exe (C:\cmder-master\vendor\git-for-windows\mingw32\bin\git.exe) but did not add my github account to PhpStorm. Whenever PhpStorm asks to add a file to git I just say no.

**Comment by fpizzuta** [comment]
Same, it pops up in the bottom right corner on my Windows machine. 
![image](https://user-images.githubusercontent.com/4976768/45985327-bbb70900-c033-11e8-9085-48572dd6ef66.png)

**Comment by susanBuck** [comment]
Under *Preferences > Version Control > Git* you can specify the *Path to Git executable*.

To find out what git executable you're computer is using, run `which git` in command line.

For example @jpersson74's computer is using `C:\cmder-master\vendor\git-for-windows\mingw32\bin\git.exe` while my Windows machine reports it's using `C:\Program Files\Git\cmd\git.exe`. For some students, you may be using the git executable that I bundled into Cmder. Any one of these will work.

Other tips about PhpStorm notifications:

1) Most notifications have a gear icon on them when you hover them, which allows you to configure the notification
2) You can also configure what notifications can pop up via *Preferences > Appearance & Behavior > Notifications*
3) Often the notification offer some way to resolve it, whether it be an option to dismiss it/ignore it in the current project, or "Configure" as @fpizzuta's screenshot shows.

**Comment by susanBuck** [comment]
Also, just to make sure we're clear - **configuring git in PhpStorm is not required**. As was noted in lecture, it's not a feature we're using in PhpStorm. 

The above info is just for those who want to configure it or at least resolve the annoying message. : )

**Comment by mdeforest** [comment]
I chose to turn Version Control integration off by going to _Preferences > Plugins_ and unchecking "Github" and "Git Integration".

**Comment by susanBuck** [comment]
I believe the issue in question here is resolved so closing this thread. If anyone still has questions feel free to continue the discussion or start a new thread.
