### ISSUE TITLE
Moving files between projects in a repositary

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#44]
Is it possible to move files between projects in a repositary? If so, what is the process? I'm scared to play around too much and delete files.

**Comment by Sud-B** [comment]
Yes I do luckily. But I moved files from both projects the repositary for the first project accidentally. Thanks for your input. I'll read through the notes and see if there's a way to fix it.

**Comment by mdeforest** [comment]
If I understand what you mean correctly, its as easy as moving files like you would normally from one project directory to the other and then initiating a commit
