### ISSUE TITLE
Loaner Computer lost ssh access to digital ocean

### ISSUE THREAD

**Issue by dickblair** [susanBuck/dwa15-fall2018#47]
Hi Class,

Unfortunately, during a storm my computer got totally fried and it would not post on startup.  Perhaps my surge protector was ineffective.  I took it to a computer repair place, and they can fix it but need a couple components from China and it will be a few weeks.  I bought a new system from them, as my old computer was more than 3 years old, figuring I can give my old one to my kids, and that should be ready any day now.  In the meantime, he was kind enough to lend me the floor model until my new computer is built.

I did all the lessons on setup over again, but I can't access digital ocean via SSH.

I reset my root password, and I can see my SSH keys in the  authorized_keys folder, but still access denied.  I can still access root if I type my password.  Also, from root if I type "ssh -T git@github.com" I see the welcome message with my user name.  
I have tried:

- generating new keys
- killing the droplet and then starting it up again
- killing services and restarting

**Comment by susanBuck** [comment]
Glad you were able to spot the difference and get it working!
