### ISSUE TITLE
Tabs as form of input

### ISSUE THREAD

**Issue by venkateshmantha** [susanBuck/dwa15-fall2018#49]
Are Bootstrap tabs/pills considered as a form of input for project 2?
<img width="520" alt="screen shot 2018-09-28 at 10 56 43 pm" src="https://user-images.githubusercontent.com/9137253/46240238-58e6aa00-c372-11e8-84a1-0120261d91a9.png">

**Comment by DoryAzar** [comment]
They are more of a layout artefact I think. Unless you want to submit the selected tab as part of your form... I believe in that case you will need to submit it as a hidden input in your form (so that would be a hidden input type).

**Comment by venkateshmantha** [comment]
I have re-designed my application to include inputs of other kind but am still using the tabs for better layout. However for their working, they require few JS libraries.
@susanBuck Is it okay to use JS libraries for the proper working of few HTML/Bootstrap elements? I can add that I don't use Javascript for any other functionality in my project.

Thanks.

**Comment by susanBuck** [comment]
@venkateshmantha Yup, it's okay to use JS libraries for some HTML/Bootstrap elements.

Also, just confirming what @DoryAzar said - I would not consider tabs a form input type (in case anyone else had the same question).
