### ISSUE TITLE
what is setting to mention type of argument?

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#50]
Hi,

As shown in lecture video, I am also getting "Undefined class string..." error if I mention argument type in function. What setting I need to change in php storm to not show error?

Thanks
Hemant

**Comment by satyapalvadi** [comment]
@hemantbajpai 
On Windows, File -> Settings -> Languages & Frameworks -> PHP -> set the PHP language level to 7.3

**Comment by pausman** [comment]
On a mac 
PhPStorm -> Preferences -> Language & Frameworks. 
Change the PHP language level
![image](https://user-images.githubusercontent.com/13261312/46248239-fc70a280-c3e4-11e8-8a7c-aaed4bc5e153.png)

**Comment by hemantbajpai** [comment]
Thanks

**Comment by susanBuck** [comment]
More screenshots here for anyone else with this question:
https://github.com/susanBuck/dwa15-fall2018/issues/46
