### ISSUE TITLE
Validation of radio buttons

### ISSUE THREAD

**Issue by pausman** [susanBuck/dwa15-fall2018#51]
So form.php does not have a validation method for a set of radio buttons.  Should I
1) Extend form.php 
2) Write a little code in the php file that processes form data to do it
3) Ignore validating it server side
?

Thanks Pat

**Comment by DoryAzar** [comment]
I would go for #2. There is prob not much to validate but if you want to use it you will prob need to do #2.

**Comment by susanBuck** [comment]
Agreed with @DoryAzar - I'd go with 2.

**Comment by jessupjs** [comment]
Hi! @pausman :: would you mind sharing what you ended doing for radio buttons?  I've also got em in mine and am considering making them have a required value with none selected as default.  Tks!

**Comment by pausman** [comment]
Well I realized that the radio buttons all had the same name value so I validated them by the name being required.  

Here is the snippet from index.php defining the buttons
```
               <div class="checkbox">
                    <input type="radio" name="shiftDirection" value="right"
                        <?= (!isset($shiftDirection) or $shiftDirection == 'right') ?
                            'checked' : '' ?>> Rotate Right or Up<br>
                    <input type="radio" name="shiftDirection" value="left"
                        <?= (isset($shiftDirection) && $shiftDirection == 'left') ?
                            'checked' : '' ?>> Rotate Left or Down<br>
                </div>
```
Now this is the validation - nothing special just using form.php
```
if ($submitted) {
    $errors = $form->validate(
        [
            'shiftDirection' => 'required'
        ]
    );
}
```
I omitted any additional validation I did.

**Comment by jessupjs** [comment]
Ah ... thanks!  I also used the `validate()` function to call `'required'`, but you sprinkled your syntactic sugar more nicely than I did.

"shiftDirection" sounds action-packed!  Good luck!
