### ISSUE TITLE
Header redirect doesn't work

### ISSUE THREAD

**Issue by venkateshmantha** [susanBuck/dwa15-fall2018#52]
I try to do a header redirect using the `header()` from my *logic.php* which intends to redirect the user to *index.php* after setting the result in the session.

However my Firefox browser won't redirect the page and throws this message:
```
The page isn’t redirecting properly
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by DoryAzar** [comment]
any chance you could show how you are using header() and a peak at your index.php?

**Comment by venkateshmantha** [comment]
Here is my use of [header()](https://github.com/venkateshmantha/dwa-p2/blob/46feba0f3f25a428310d466a2de2e07fab921095/converter.php#L27) and my [index.php](https://github.com/venkateshmantha/dwa-p2/blob/master/index.php)

**Comment by DoryAzar** [comment]
The php require statements need to be on the very top of the file in index.php:
```php
<?php
require ‘filename’;
require ‘filename’;
?>
<html 
....
</html>
```

**Comment by DoryAzar** [comment]
Ok. Well you either require converter or you redirect. You can’t do both. If you require converter.php like you did then the content of it is as if it is in the index.php. 

remove the redirect from converter.php or remove the require from index.php

**Comment by venkateshmantha** [comment]
You are right, that works. Great eye.

Thanks!

**Comment by malrice** [comment]
Thanks! This solved one of my (many) problems too!
