### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by fpizzuta** [susanBuck/dwa15-fall2018#55]
My p1 production url works fine. I set p2 up the same way. The files are in the p2 directory via a git pull. What could be causing the 500 error?

**Comment by susanBuck** [comment]
Can you share the following info with us:

1. Your p1 URL
2. Your p2 URL
3. The full contents of your `/etc/apache2/sites-enabled/000-default.conf` file on DigitalOcean
4. The output of `ls -la /var/www/html` on DigitalOcean (this will show us all the directories in your document root)

**Comment by fpizzuta** [comment]
1.  p1.pizzuta.com
2.  p2.pizzuta.com

3.
root@dwa:/etc/apache2/sites-enabled# cat 000-default.conf                                    
<VirtualHost *:80>                                                                           
        ServerAdmin webmaster@localhost                                                      
        DocumentRoot /var/www/html                                                           
                                                                                             
        <Directory /var/www/html/>                                                           
            Options Indexes FollowSymLinks                                                   
            AllowOverride All                                                                
            Require all granted                                                              
        </Directory>                                                                         
                                                                                             
        ErrorLog ${APACHE_LOG_DIR}/error.log                                                 
        CustomLog ${APACHE_LOG_DIR}/access.log combined                                      
                                                                                             
        <IfModule mod_dir.c>                                                                 
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm     
        </IfModule>                                                                          
                                                                                             
</VirtualHost>                                                                               
                                                                                             
<VirtualHost *:80>                                                                           
  ServerName p1.pizzuta.com                                                                  
  DocumentRoot "/var/www/html/p1"                                                            
  <Directory "/var/www/html/p1">                                                             
    AllowOverride All                                                                        
  </Directory>                                                                               
</VirtualHost>                                                                               
                                                                                             
<VirtualHost *:80>                                                                           
  ServerName p2.pizzuta.com                                                                  
  DocumentRoot "/var/www/html/p2"                                                            
  <Directory "/var/www/html/p2">                                                             
    AllowOverride All                                                                        
  </Directory>                                                                               
</VirtualHost>                                                                               
                                                                                             
<VirtualHost *:80>                                                                           
  ServerName p3.pizzuta.com                                                                  
  DocumentRoot "/var/www/html/p3"                                                            
  <Directory "/var/www/html/p3">                                                             
    AllowOverride All                                                                        
  </Directory>                                                                               
</VirtualHost>                                                                               
                                                                                             
<VirtualHost *:80>                                                                           
  ServerName p4.pizzuta.com                                                                  
  DocumentRoot "/var/www/html/p4"                                                            
  <Directory "/var/www/html/p4">                                                             
    AllowOverride All                                                                        
  </Directory>                                                                               
</VirtualHost>                                                                               
root@dwa:/etc/apache2/sites-enabled#     

4.
root@dwa:/var/www/html# ls -la                                   
total 28                                                         
drwxrwxr-x 5 www-data www-data 4096 Sep 24 23:39 .               
drwxrwxr-x 3 www-data www-data 4096 Sep 12 15:43 ..              
drwxr-xr-x 4 root     root     4096 Sep 15 23:34 helloworld      
-rw-rw-r-- 1 www-data www-data 6595 Sep 12 15:43 index.html      
drwxr-xr-x 4 root     root     4096 Sep 16 16:57 p1              
drwxr-xr-x 3 root     root     4096 Oct  2 00:15 p2              
                                                    

thanks

**Comment by fpizzuta** [comment]
Here is the p2 folder as well

root@dwa:/var/www/html/p2# ls -la                               
total 44                                                        
drwxr-xr-x 3 root     root     4096 Oct  2 00:15 .              
drwxrwxr-x 5 www-data www-data 4096 Sep 24 23:39 ..             
drwxr-xr-x 8 root     root     4096 Oct  2 00:28 .git           
-rw-r--r-- 1 root     root        6 Oct  2 00:15 .gitignore     
-rw-r--r-- 1 root     root      360 Oct  2 00:15 Event.php      
-rw-r--r-- 1 root     root     6219 Oct  2 00:15 Form.php       
-rw-r--r-- 1 root     root      278 Oct  2 00:15 README.md      
-rw-r--r-- 1 root     root     3506 Oct  2 00:15 index.php      
-rw-r--r-- 1 root     root        0 Oct  2 00:15 p2.css         
-rw-r--r-- 1 root     root      950 Oct  2 00:15 p2.php         
-rw-r--r-- 1 root     root      238 Oct  2 00:15 p2Logic.php    
root@dwa:/var/www/html/p2#

**Comment by DoryAzar** [comment]
You are requiring `p2logic.php` in the index.php but it seems like the real file is p2Logic.php (the L is capitalized). 
This might be the source of your problems.
While at it, make sure that the require statement does not use ().

**Comment by fpizzuta** [comment]
That was it! Works fine on Windows. Thank you for all the help.

**Comment by susanBuck** [comment]
Good catch @DoryAzar!

This is a great example of why it's always good to test early on production. Mostly, things should work the same, but you never know when small operating system/configuration differences can cause problems.


ps - @fpizzuta  - I edited your above posts to make the various outputs of information easier to read by surrounding them in Markdown code fences. I wanted to note this in case you were wondering why your posts were suddenly displaying differently. [More info here...](https://github.com/susanBuck/dwa15-fall2018/issues/1)
