### ISSUE TITLE
Bookmarking lecture videos

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#57]
Is there any way to bookmark a point in lecture videos?

**Comment by DoryAzar** [comment]
I think youtube does allow to do this.
Just add `?t=starttimeinseconds` at the end of the URL of the video.

**Comment by susanBuck** [comment]
Or, right click the video and choose *Copy video URL at current time*

**Comment by Sud-B** [comment]
Thank you!
