### ISSUE TITLE
Dropdown Error

### ISSUE THREAD

**Issue by rdudeney** [susanBuck/dwa15-fall2018#59]
Is there any way to prefill the dropdown box after an error in the form. After an error in the data elsewhere in the form, the dropdown box returns to the message `Choose one...` instead of prefilling with the last option chosen. Is this the proper function of the dropdown?

**Comment by jessupjs** [comment]
Hi @rdudeney!

As far as I know you'll, need to include something like below in each `<option>` element within your `<select>` element:

```
<select name='yourName'>
    <option value='value1' <?php if (isset($yourName) && $yourName == "value1") echo 
        "selected='selected'" ? >>value1</option>
    <option value='value2' <?php if (isset($yourName) && $yourName == "value2") echo 
        "selected='selected'" ? >>value2</option>
</select>
```

Good luck!

**Comment by susanBuck** [comment]
👍to @jessupjs's answer!

I'll add that you can simply echo `"selected"`, and do not need to echo `"selected='selected'"`

For a similar example, see the dropdown examples here: <http://php.dwa15.com/forms-inputs>

**Comment by dickblair** [comment]
> For a similar example, see the dropdown examples here: http://php.dwa15.com/forms-inputs
Professor, should we be able to see the source of these php files?  I only ever get blank files when I try to download them.

**Comment by susanBuck** [comment]
@dickblair If you revisit [Week 3](https://dwa15.com/week/3)'s outline, scroll to the bottom - I referenced both the production and github code links for both foobooks0 and the basic php examples.

**Comment by susanBuck** [comment]
Closing this post due to inactivity from original poster, but feel free to re-open or start a new thread if any questions are still pending.
