### ISSUE TITLE
Logic/Display structure

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#61]
Would it be acceptable to have a structure with the first block of code in PHP to assign variables, second block to input information with HTML and then a third block to validate and process the information in PHP, then a fourth block to output the information in either PHP or HTML, or is it better to try and have only 2 separate boxes?

**Comment by DoryAzar** [comment]
What's a block according to you?

**Comment by Sud-B** [comment]
I just checked on this. I had thought it was a chunk of completed code in one language but it seems it is a chunk of code in one of indentation level. I'm glad you asked the question. Which is it according to you?

**Comment by DoryAzar** [comment]
it could mean different functions in a php file. It could mean different functions in a php class.
Or it could simply mean a sequential code that will be executed from top to bottom and included in another code. Perhaps a url to your code file or a snapshot of your code can help us understand what you have in mind.

**Comment by Sud-B** [comment]
Thanks Dory. I changed my structure around. I think what I have should be fine now with functions totally distinct.
