### ISSUE TITLE
W3 Validator errors, not sure how to fix?

### ISSUE THREAD

**Issue by q0w9e8r7t6y5** [susanBuck/dwa15-fall2018#62]
Hello all!

Trying to run project 2 through the w3validator and keep running into some odd errors.

Git link: https://github.com/q0w9e8r7t6y5/p2
URL: www.sy-dwa15.me/p2

After continuing through the first page and then submitting an order, we see the order come up at the bottom. I then did view source and copy/pasted that into the validator. As far as I can tell, the errors it throws are code I need for the php to work (because I'm trying to auto-select a default when the page loads)?

Thanks for the help,
Sishir

<img width="376" alt="screen shot 2018-10-03 at 11 33 25 am" src="https://user-images.githubusercontent.com/31637207/46421582-68624c00-c700-11e8-99c2-0516c6a4df57.png">

<img width="512" alt="screen shot 2018-10-03 at 11 35 02 am" src="https://user-images.githubusercontent.com/31637207/46421587-6c8e6980-c700-11e8-8e2e-a520846fb041.png">

**Comment by DoryAzar** [comment]
you do have a duplicate. In the input you field you `checked=‘checked’ checked’`. For the browser these are one and the same. You should either use `checked=‘checked’` OR just `checked` but not both at the same time. 
Personally i prefer to use `checked` alone.

**Comment by q0w9e8r7t6y5** [comment]
> you do have a duplicate. In the input field you have `checked=‘checked’ checked`. For the browser these are one and the same. You should either use `checked=‘checked’` OR just `checked` but not both at the same time.

That's how it is displaying in the "view source," but in my php file, there is no duplicate. I also tried using just `checked` instead of `checked='checked'`, and it was throwing the same error.

https://github.com/q0w9e8r7t6y5/p2/blob/master/order.php

Lines 31, 64, and 78

```<input type='radio'
                   name='type'
                   value='burrito'
                   checked='checked' <?php if (isset($type) and $type == 'burrito') echo 'checked' ?>> Burrito<br>
```

**Comment by DoryAzar** [comment]
I got into your code, I removed all the `checked = checked` that you have in several places.
Your code works just fine and the validator returns no error.
Make sure you remove it everywhere, otherwise nuhtml will stil complain about it

**Comment by q0w9e8r7t6y5** [comment]
> Make sure you remove it everywhere, otherwise nuhtml will stil complain about it

Yup, if I remove them, the errors will go away, but I need the radio buttons checked.

Guess I will have to email the professor...

Thanks for the help @DoryAzar !

**Comment by SandiAnderson** [comment]
I think the error is because you have the `checked='checked'` in your html and then the php checking for the value _`<?php if (isset($type) and $type == 'burrito') echo 'checked'`_ so if the php evaluates to checked it is showing up twice. If the type is not set is the value showing as checked?

**Comment by susanBuck** [comment]
For the benefit of other students reading this thread/facing a similar issue, I want to elaborate on what the fix was.

As @SandiAnderson noticed, there was a hard-coded `checked='checked'` in the HTML, as well as some PHP logic that was potentially echoing `checked`.

This occurred specifically on the first radio option because @q0w9e8r7t6y5 was trying to specify that radio should be selected on initial page load (i.e. the default value).

Here's what that code looked like: 
```php
<input type='radio'
    name='beans'
    value='Black Beans'
    checked='checked'
    <?php if (isset($beans) and $beans == 'Black Beans') echo 'checked' ?>> Black Beans<br>
```

To fix, we removed `checked='checked'` and expanded on the conditional so it would echo checked if a) `$beans` was not yet set (initial page load) *or* if `$beans` was set *and* it was set to *Black Beans*

The resulting code looked like this:
```php
<input type='radio'
    name='beans'
    value='Black Beans'
    <?php if (!isset($beans) or (isset($beans) and $beans == 'Black Beans')) echo 'checked' ?>> Black Beans<br>
```
