### ISSUE TITLE
Permission Denied when Creating Local Host URL

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#63]
Hi,
I have never encountered this message before, and I completed the foobooks Laravel setup without this issue. I am attaching a screenshot. If anyone knows how to get the permission to add my local url, I would love the advice.
<img width="599" alt="screen shot 2018-10-04 at 1 57 05 pm" src="https://user-images.githubusercontent.com/35276882/46496591-0f68e580-c7de-11e8-900a-f973403340d1.png">

**Comment by pausman** [comment]
did you try sudo vim /private/etc/hosts?

**Comment by cpowell1** [comment]
Thanks so much, that did the trick. I didn't realize the sudo was missing.
