### ISSUE TITLE
how much time it takes to create new project in laravel

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#64]
Hi,

I gave this command and it is not taking lots of time in windows:

composer create-project laravel/laravel foobooks "5.7.*" --prefer-dist

it is stuck in updating dependencies for last more than 15 minutes with no errors. Is it normal?

Thanks
Hemant

**Comment by hemantbajpai** [comment]
it took me 30 minutes to complete, not sure what is wrong.

**Comment by DoryAzar** [comment]
so it’s done? that’s good. It might have been internet connection, older computer processor... lot of factors. glad it completed

**Comment by hemantbajpai** [comment]
thanks
