### ISSUE TITLE
Troubleshoot with php configuration

### ISSUE THREAD

**Issue by vanillacandy** [susanBuck/dwa15-fall2018#65]
The instruction at page https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/composer-mac.md  shows we are suppose to do PHP from command line check, my output expectation isn't the same to the instruction, then how to reconfigure php to the right path?

Expectation: 
$ which php
/Applications/MAMP/bin/php/php7.2.7/bin/php

My outcome:
/usr/bin/php

Expectation: 
$ php --ini
Configuration File (php.ini) Path: /Applications/MAMP/bin/php/php7.2.7/conf
Loaded Configuration File:         /Library/Application Support/appsolute/MAMP PRO/conf/php7.2.7.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

My outcome:
Configuration File (php.ini) Path: /etc
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

**Comment by pausman** [comment]
You need to add to the PATH variable. Instructions at
https://github.com/susanBuck/dwa15-fall2018/blob/master/command-line/path.md

**Comment by vanillacandy** [comment]
Oh, thank you!
