### ISSUE TITLE
Initializing an Array of data for view - best practice

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#67]
When using a multidimensional array with a form is it acceptable to define the array (2 lines of PHP code) sequentially before the code for the HTML form or is it better to separate them into a separate PHP file? Could this be part of the logic (PHP) file or is it better separate?

**Comment by Sud-B** [comment]
Yes it is an array of values and options. Thank you, I'll separate it out into the logic PHP. Shall I leave this open to circle back to for Project 3?

**Comment by susanBuck** [comment]
Sure, let's keep it open. 👍

**Comment by susanBuck** [comment]
Circling back on this -

Last week (7) we saw how data can be defined/retrieved in a config.
We also saw how data can be passed to a view.

As an example, let's say I'm building the [bill splitter](https://s3.amazonaws.com/dwa15.com/wireframe-bill-splitter@2x.png) and I wanted to codify the tip percentages (`ok 15%`, `good 18%`, `great 20%`).

I could set this up as a config, let's say in `config/app.php`:
```php
<?php
return [
    'tipPercents' => [
        'ok' => 15, 
        'good' => 18,
        'great' => 20
    ],
    [...etc...
];
```

With that defined, I could make it available when returning my view:
```php
return view('billSplitter')->with([
    'tipPercents' => config('app.tipPercents')
];
```

Then in the view I could use this data to build a drop-down:
```html
<select name='tip'>
    @foreach($tipPercents as $descriptor => $percent)
        <option value='{{ $percent }}'>{{ $descriptor }}</option>
    @endforeach
</select>
```

If I only anticipated needing these values in one spot in the app, defining it in the config may be a little excessive. Instead, I could define the data right in the controller:

```php
$tipPercents = [
        'ok' => 15, 
        'good' => 18,
        'great' => 20
];

return view('billSplitter')->with([
    'tipPercents' => $tipPercents
];
```

**Comment by susanBuck** [comment]
Closing this post, but feel free to continue the discussion or post a new thread if any questions are still pending.

**Comment by Sud-B** [comment]
Thanks Susan!
