### ISSUE TITLE
PHP Array in logic file won't populate

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#69]
Hello. I'm stuck on my logic file for Project 2 after separating the code. I've trimmed it down considerably and the code validates but my output doesn't populate with the values from the Array keys. This is what I have:

`<?php
$order = array("Name"=>" ", "Place"=>" ", "Bread"=>" ", "Protein"=>" ", "Salad"=>" ", "Drink"=>" " );
echo "Hello ". $order["Name"] . ", your order ". $order["Place"] . " for a ". $order["Bread"] . "Sandwich ". "with ". $order["Protein"] . "and ". $order["Salad"] . "as well as ". $order["Drink"] . "will be ready in 30 minutes!";
?>`

**Comment by mihika-shilpi** [comment]
Well currently your array is empty right? The Key `Name` has no associated value, unless you're populating that with the form (which I assume) but what is your code for that, and is it running before this?

**Comment by Sud-B** [comment]
Thanks! Yes it populates from the form. This is the code for the form.

`<?php 
require('p2logic.php');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sam's Sandwich shop lunch special</title>
    
    <link rel="stylesheet" href="p2dwa.css">
    <meta charset="utf-8"/>
</head>
<body>
    <h1>Sam's Sandwich shop</h1>
    <h2>Menu and order form - lunch special $6.50/- with complimentary drink</h2>
    <img src="sw.jpg" alt="Sandwich"/>
    <p>Enter the order information for your Sandwich below:</p>

    <form method="post" action="p2logic.php">
        <fieldset>
            <strong>Customer name</strong>
            <br>
            <input type="text" name="order[Name]" id="Customer">
            <br>
            <input type="radio" name="order[Place]" id="ToStay" value="ToStay" />
            <label for="Stay">Stay</label>
            <br>
            <input type="radio" name="order[Place]" id="Togo" value="Togo"/>
            <label for="Togo">To go</label>
            <br>
        </fieldset>
        <br>
        <fieldset>
            <strong>Choice of bread</strong>
            <br>
            <input type="radio" name="order[Bread]" id="Bread_S" value="Sourdough" />
            <label for="Bread_S">Sourdough Bread</label>
            <br>
            <input type="radio" name="order[Bread]" id="Bread_R" value="Rye" />
            <label for="Bread_R">Rye Bread</label>
            <br>
            <input type="radio" name="order[Bread]" id="Bread_W" value="Wholewheat" />
            <label for="Bread_W">Wholewheat</label>
            <br>
        </fieldset>
        <fieldset>
            <br>
            <strong>Choice of protein</strong>
            <br>
            <input type="radio" name="order[Protein]" id="Protein_H" value="Ham" />
            <label for="Protein_H">Ham</label>
            <br>
            <input type="radio" name="order[Protein]" id="Protein_S" value="Smoked Salmon" />
            <label for="Protein_S">Smoked Salmon</label>
            <br>
            <input type="radio" name="order[Protein]" id="Protein_C" value="Cheddar" />
            <label for="Protein_C">Cheddar</label>
            <br>
        </fieldset>
        <fieldset>
            <br>
            <strong>Choice of Salad</strong>
            <br>
            <input type="radio" name="order[Salad]" id="Salad_L" value="Lettuce" />
            <label for="Salad_L">Lettuce</label>
            <br>
            <input type="radio" name="order[Salad]" id="Salad_T" value="Tomato" />
            <label for="Salad_T">Tomato</label>
            <br>
            <input type="radio" name="order[Salad]" id="Salad_A" value="Arugula" />
            <label for="Salad_A">Arugula</label>
            <br>
        </fieldset>
            <br>
        <fieldset>
            <strong>Drinks</strong>
            <br>
            <br>
            <select name="order[Drink]">
            <optgroup label ="Choice of drink">
                <option value="Icedtea">Iced Tea</option>
                <option value="Orangej">Orange Juice</option>
                <option value="Applej">Apple Juice</option>
                <option value="Minwater">Mineral Water</option>
            </optgroup>
            </select>
        </fieldset>
            <br>
            <input type="submit" name="Todo" value="Place Order"/>
            <br>
    </form>
</body>
</html>
`

**Comment by DoryAzar** [comment]
If it populates from the form then you need to make sure that `$order` takes its values from the form. Right it looks like you are overriding it with empty values before displaying it.

**Comment by Sud-B** [comment]
That makes sense. I was worried about that but am trying to separate the PHP code into a separate file. Maybe I initiate the Array in a second PHP file? Seems messy. It's tying into my other open issue.

**Comment by DoryAzar** [comment]
Your form is submitting to p2logic.php so make sure that after the form inputs are validated in p2logic.php to save the output in a Session variable let’s say `$_SESSION[‘order’]`.
Once you have done that, create another php file, let’s call it output.php just for the sake of this conversation. In output.php make sure that `$order = $_SESSION[‘order’]`. Lastly, let your display file `require ‘output.php’`. I believe this would give you what you need

**Comment by Sud-B** [comment]
Thanks Dory. I'll give it a go.
