### ISSUE TITLE
Understanding Composer b/w local and production environments

### ISSUE THREAD

**Issue by jessupjs** [susanBuck/dwa15-fall2018#70]
Good afternoon!

I hope I correctly understand that vendor dependencies are not passed from local to production using Git version control.  Instead within the production directory, Composer uses the composer.json / composer.lock files to install or update those dependencies so that the versions match.  

So in a way, aren't vendor dependencies, at least indirectly, still controlled by version control?  Also would the reason for .gitignore-ing the "Vendors" folder be just to prevent a situation where an author dug into the dependencies and altered or messed up the code there (i.e., best practice). 

Any insight would be welcome - just trying to make sure I'm understanding how Composer works correctly, especially as it exists as a customized step in the deployment process.  For example, if during the course of a project, we update our local Laravel application and the included dependencies, should we also make sure to run something like `$ composer update --no-dev` whenever we `$ git pull`?

Tks!

**Comment by susanBuck** [comment]
>> vendor dependencies are not passed from local to production using Git version control

This is true.

>> Composer uses the composer.json / composer.lock files to install or update those dependencies so that the versions match.

When we run `composer install --no-dev` it's the `composer.lock` file that composer uses. The `composer.lock` file contains a snapshot of the versions that were used locally when referring to `composer.json`. This ensures that your local version and your production version are always in sync with the version numbers they're using for packages.

>> So in a way, aren't vendor dependencies, at least indirectly, still controlled by version control?

In a way they are; the dependency files themselves are just not included in version control.

>> Also would the reason for .gitignore-ing the "Vendors" folder be just to prevent a situation where an author dug into the dependencies and altered or messed up the code there (i.e., best practice).

It should be noted that some teams actually *do* include their vendors folder in their version control. That's not the approach we are taking, though, that's not the one that Composer recommends. For the reasons why, refer to this documentation: [Should I commit the dependencies in my vendor directory?](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md).

>> just trying to make sure I'm understanding how Composer works correctly, especially as it exists as a customized step in the deployment process. For example, if during the course of a project, we update our local Laravel application and the included dependencies, should we also make sure to run something like $ composer update --no-dev whenever we $ git pull?

Running `composer install --no-dev` will become part of your deployment process after running `get pull`. I'll cover this in full detail in Week 7 when we focus on packages. 

All good questions! It shows you're thinking about the underlying process.

**Comment by susanBuck** [comment]
I just labeled this thread is pending-future-lecture-topic; let's keep it open until Week 7 as I think it has some good questions/info.

**Comment by susanBuck** [comment]
Now that this material was covered in Week 7, I'm going to close this topic - but feel free to continue the discussion or start a new thread if there are any pending questions.

For reference, here are the specific notes that details the different composer commands to use on local vs. production: [Package examples: Deploying packages to production](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/packages-examples.md#deploying-packages-to-production)
