### ISSUE TITLE
Deploying p3 to production after installing Laravel IDE Helper 

### ISSUE THREAD

**Issue by jpersson74** [susanBuck/dwa15-fall2018#75]
I was able to get my initial p3 up and running on my Digital Ocean production server but after going through the class lectures and notes I'm running into issues updating my project after the section on Facades and the Laravel IDE helper. Everything runs fine locally. When I deploy to production I get the following:

Error from the command line:
```
root@jpersson-DWA-2018:/var/www/html/p3# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Application.php line 636:

  Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

```

Error in the Laravel.log:

```

 GNU nano 2.9.3                                laravel.log

[2018-10-14 14:21:31] local.ERROR: Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not fo$
[stacktrace]
#0 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(568): Illumin$
#1 /var/www/html/p3/app/Providers/AppServiceProvider.php(27): Illuminate\\Foundation\\Application->r$
#2 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(572): App\\Pr$
#3 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): I$
#4 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(548): Illumin$
#5 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.p$
#6 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illumin$
#7 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Illu$
#8 /var/www/html/p3/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(120): Illu$
#9 /var/www/html/p3/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Com$
#10 {main}
"}
```

Any suggestions would be greatly appreciated!

**Comment by hemantbajpai** [comment]
did you do composer install --no-dev?

**Comment by mdeforest** [comment]
Hi @jpersson74!

Assuming you followed all the directions correctly pertaining to the ide-helper, I wonder if you changed the APP_ENV to `production` from within the `.env` file. If you have not, this could explain your issue. The composer commands would be running as if you were in a development environment.

**Comment by jpersson74** [comment]
That was the issue - thanks Michaela!

**Comment by ccrane** [comment]
> Hi @jpersson74!
> 
> Assuming you followed all the directions correctly pertaining to the ide-helper, I wonder if you changed the APP_ENV to `production` from within the `.env` file. If you have not, this could explain your issue. The composer commands would be running as if you were in a development environment.

@jpersson74 Nice catch!
