### ISSUE TITLE
Bonus material (Week 7): Deployment script

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2018#77]
Deploying code changes to production involves running several commands - you have to git `add` and `commit` your files locally, then `push` the commit(s), then SSH into your production server and `cd` into the appropriate project directory, then run git `pull` to synchronize with the latest changes. 

Additionally, in this week's (7) lecture material, I explain that you also need to start running the command `composer install --no-dev` to make sure your production packages are up to date.

Long story short, it's a lot of commands just to get your changes to production. 

Because of this, it's common to create deployment scripts that can help expedite/automate this process.

If you're interested in learning more about this, read the following (optional) note set: [Deployment script](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/deployment-script.md)

I tested the deployment script on both Mac/Win, but let me know if you run into any issues on your end when implementing.

**Comment by Sud-B** [comment]
Thank you!

**Comment by fpizzuta** [comment]
This is great. Is it common to have one for setting up a project as well?

**Comment by susanBuck** [comment]
@fpizzuta Good Q - I'd say it depends on the kind of work you're doing. If you build a lot of new projects frequently (e.g. you're a web dev shop that works with clients) automating that process would probably be helpful.

**Comment by susanBuck** [comment]
@fpizzuta On a follow-up/related note, I do use a script that helps me quickly clone/deploy student projects locally so I can help troubleshoot/use when grading.

```
#!/bin/sh

# Check parameters were passed in
if [ -z "$1" ]; then
    echo "Missing studentName parameter"
    exit
fi

if [ -z "$2" ]; then
    echo "Missing githubUrl parameter"
    exit
fi


# Variables
DESTINATION="students"
STUDENT_NAME=$1
REPO_URL=$2
REPO_NAME=$(echo $REPO_URL | awk -F/ '{print $NF}' | sed -e 's/.git$//')
LOCAL_REPO=$DESTINATION"/"$STUDENT_NAME"/"$REPO_NAME"/public"


# Report details
echo '---- DETAILS ---- '
echo "STUDENT_NAME: ${STUDENT_NAME}"
echo "REPO_URL: ${REPO_URL}"
echo "REPO_NAME: ${REPO_NAME}"
echo "DESTINATION: ${DESTINATION}"
echo "LOCAL REPO: ${LOCAL_REPO}"


# Make directory
echo '---- MAKE DIRECTORY ---- '
cd $DESTINATION
rm -rf $STUDENT_NAME # Remove the directory if it's already there
mkdir $STUDENT_NAME
cd $STUDENT_NAME


# Clone repo
echo '---- CLONE PROJECT ---- '
git clone $REPO_URL $REPO_NAME
cd $REPO_NAME

if [ -f "composer.json" ]
then
	# Create database
    echo '---- CREATE DATABASE ---- '
    /Applications/MAMP/Library/bin/mysql -uroot -proot -e "drop database student_${STUDENT_NAME}"
    /Applications/MAMP/Library/bin/mysql -uroot -proot -e "create database student_${STUDENT_NAME}"

    # Create env file
    echo '---- CREATE .env FILE ---- '
    cat >.env <<EOL
APP_ENV=local
APP_DEBUG=true
APP_URL=http://localhost
APP_KEY=yourkeyhere

DB_HOST=localhost
DB_DATABASE=student_${STUDENT_NAME}
DB_USERNAME=root
DB_PASSWORD=root
EOL

    echo '---- CHANGE PERMISSIONS ---- '
    chmod -R 777 storage
    chmod -R 777 bootstrap/cache

    echo '---- COMPOSER INSTALL ---- '
    composer install

    echo '---- GENEREATE KEY ---- '
    php artisan key:generate

fi
```

**Comment by Sud-B** [comment]
Thank you Susan. I'm saving this.
