### ISSUE TITLE
Composer Error when running IDE Helper Command

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#78]
Hi,

I get this error when running the IDE helper command in the Week 6 lecture notes. Do I need to update the Laravel software, or does anyone know what causes this issue?

<img width="560" alt="screen shot 2018-10-17 at 9 58 59 am" src="https://user-images.githubusercontent.com/35276882/47169664-bc0c9200-d2c9-11e8-856c-4c40841d1977.png">

**Comment by susanBuck** [comment]
Any chance your network might be running on a firewall, a protected work network, etc.?

Also, run `php -i | grep -i ssl` and share the output with us. This will give us info about your PHP install and the SSL module (which may be related).

Finally, run and share the output of `composer diagnose`.

The above commands I got from a search for `Composer\Downloader\TransportException` which lead to [this post](https://github.com/composer/composer/issues/4388).

**Comment by cpowell1** [comment]
Here are the two outputs for those commands... it seems like composer is okay unless I am missing something?
<img width="743" alt="screen shot 2018-10-19 at 1 44 41 pm" src="https://user-images.githubusercontent.com/35276882/47237672-78875600-d3a5-11e8-8078-83bb9d6852c4.png">
<img width="739" alt="screen shot 2018-10-19 at 1 45 25 pm" src="https://user-images.githubusercontent.com/35276882/47237675-7a511980-d3a5-11e8-98c6-d7d59f91e1de.png">

**Comment by susanBuck** [comment]
For comparison, here's the result of `composer diagnose` on my system:

```
~/Sites   $ composer diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.2
PHP version: 7.2.8
PHP binary path: /Applications/MAMP/bin/php/php7.2.8/bin/php
```

Note my `PHP binary path` points to an install of PHP in MAMP, whereas yours is pointing to `/usr/bin/php` which *could* be part of the problem.

1. Can you re-run through this note set - [PATH](https://github.com/susanBuck/dwa15-fall2018/blob/master/command-line/path.md) - and confirm your command line PHP is pointing to an installation of PHP (> 7.2 ) in MAMP? 

2. Can you confirm `composer require --dev barryvdh/laravel-ide-helper` is the command that is triggering this error and can you run it again and make sure error is still occuring (in the event that it was a momentary blip). If the error is still occuring, can you copy/paste the full output in your reply? (Screenshot is helpful for seeing the error but it's easier to troubleshoot if we copy bits of text from the error itself).

3. Can you let us know if you're running this command on a home, work, or public (e.g. coffee shop) network?

**Comment by cpowell1** [comment]
<img width="833" alt="screen shot 2018-10-24 at 7 52 09 am" src="https://user-images.githubusercontent.com/35276882/47431583-be576c00-d761-11e8-94c2-4b2976264ae5.png">

I received this output, so I think I am good to go! Thank you for the instructions.
