### ISSUE TITLE
composer error when deployed on DigitalOcean. 

### ISSUE THREAD

**Issue by pingji00** [susanBuck/dwa15-fall2018#80]
When I tried to run "composer install --no-dev" on my P3, I got the error message as attached.  

<img width="708" alt="screen shot 2018-10-20 at 5 19 44 pm" src="https://user-images.githubusercontent.com/12189712/47260596-659b8100-d48c-11e8-9b29-be201b910e63.png">

Then I inputted "composer require --dev barryvdh/laravel-ide-helper" locally then sync it again, the issue is still there. 

The foobooks project was totally fine, though, so I did mess up something. Any suggestions would be appreciated.

**Comment by DoryAzar** [comment]
Hmmm A couple of things:
1. When you installed the IDE helper locally, did you make sure to require it just for dev? 
2. Does your digital ocean .env say it’s « production » not « local » ?
3. Does your digital ocean .env set debug to false?

Whatever it is I think the solution can be simple:
- Locally: make sure the IDE Helper is only in « require-dev » in the package.json. If it is not then move it to require-dev and run composer update.
- push all the changes resulting from the local cleanup to github 
- Delete the Digital Ocean folder of your project and clone it again.
- Make sure that .env on digital ocean is set to production not local
- Make sure that .env on digitial ocean sets debug false
- Then you absolutely need to do `composer install —no-dev` on digital ocean

**Comment by pingji00** [comment]
Thank you so much for your help!!
Problem solved by changing the .env to production.
