### ISSUE TITLE
All logic should be in controller?

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#83]
Hi,

In foobooks0 we created a Books class and encapsulated logic there. In foobooks we added everything to controller. Is it right way or still we can create a separate class to put all calculations there?

Thanks
Hemant

**Comment by susanBuck** [comment]
Right now we are building a lot of the logic into the controller, in the interest of simplicity, but as we progress I'll show you how to better organize your logic code into outside classes as things grow more complex.

**Comment by hemantbajpai** [comment]
thanks
