### ISSUE TITLE
Project 3 - displaying with "Flash"

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#86]
For Project 3, would "flash" with Laravel be a good way to display the form information with the "GET" command?

**Comment by susanBuck** [comment]
Sure - that's how I did it in the Foobooks search example - https://github.com/susanBuck/foobooks/blob/master/app/Http/Controllers/BookController.php#L86

**Comment by Sud-B** [comment]
Thank you!
