### ISSUE TITLE
what is best way to show old values on error and keep current values without error

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#88]
Hi,

When user provides invalid input in form we use value='{{ old('lengthOfPassword') }}'> to show error input. But if the user provides valid input and got the expected result, still I want to show the user his input. I was able to do that with value='{{ $lengthOfPassword }}'>. What is the best way to get both behaviors?

Thanks

**Comment by hemantbajpai** [comment]
Not sure why but old does not work for me in both cases. On errors it returns me last value but when input is valid and i get desired output but all inputs are removed. here is my project: https://github.com/hemantbajpai/p3

Let me know if you find out any errors in logic?

**Comment by hemantbajpai** [comment]
actually old('lengthOfPassword', $lengthOfPassword) worked for both cases. Is it the best way?

**Comment by DoryAzar** [comment]
It is looking for old and if old is not set it’s taking the default value which I believe is coming from your session.
So yes after looking at your code this could work for you.

But I do suspect that your “old” values are getting overridden in the redirection process. I will familiarize myself with the GET process and get back to you... Unless somebody jumps in.

**Comment by susanBuck** [comment]
`old('lengthOfPassword')` should be sufficient for the scenario you describe (form that redirects back to itself to show results and prefill form).

Reference: [Laravel : Helpers : old:](https://laravel.com/docs/5.7/helpers#method-old)
![image](https://user-images.githubusercontent.com/237711/48007500-cb6f4600-e0e5-11e8-8e0f-fa281195ac7f.png)

The `old` method extracts data from the form from the previous request. You specify what data you want as the first argument. (Optionally, you can include a second argument which will be the default value if the first value is not available.)

Knowing this, let's run through some examples...

A. Visitor enters an **invalid** length, validation fails, we're returned to the form and the value they had entered is prefilled.
```php
<input type='text' name='lengthOfPassword' value='{{ old('lengthOfPassword') }}'>
```

B. Visitor enters a **valid** length, validation passes, you redirect the user back to the form, and again the value they had entered is prefilled:
```php
<input type='text' name='lengthOfPassword' value='{{ old('lengthOfPassword') }}'>
```

Notice in both these cases, we always have a value in the request for `lengthOfPassword` - thus it shouldn't make a difference if you had used `old('lengthOfPassword', $lengthOfPassword)` b/c that second argument (the default) would never be used.

The exception is initial page load, when there's no form request to get `lengthOfPassword` from.

In that case, the following should work, it would just leave the value blank:
```php
<input type='text' name='lengthOfPassword' value='{{ old('lengthOfPassword') }}'>
```

Alternatively you could pre-fill with some logical value (e.g. `4`):
```php
<input type='text' name='lengthOfPassword' value='{{ old('lengthOfPassword', 4) }}'>
```

**Comment by hemantbajpai** [comment]
For me case B does not work if I only specify one argument in old method. Do you see any obvious mistake in https://github.com/hemantbajpai/p3 project? Is there anything wrong in specifying 2 argument in old method?

**Comment by susanBuck** [comment]
@jessupjs `old` works in conjunction with the redirect that happens as a result of validation failure. 

Under the hood, the validate method is essentially doing these three things:

1. Is data invalid? If so...
2. Flash data to the session
3. Redirect back

If the data *is* valid, step 2 and 3 does not happen.

If you're doing your own redirect (i.e. it's not happening implicitly as part of validation), you need to do something to make that old data available, similar to what we did in [Foobook's search method](https://github.com/susanBuck/foobooks/blob/c08bffd2c8bc08dc7b177e77e070d3758982f0bf/app/Http/Controllers/BookController.php#L87):

```php  
# Redirect back to the search page w/ the searchTerm *and* searchResults (if any) stored in the session
# Ref: https://laravel.com/docs/redirects#redirecting-with-flashed-session-data
return redirect('/books/search')->with([
    'searchTerm' => $searchTerm,
    'caseSensitive' => $request->has('caseSensitive'),
    'searchResults' => $searchResults
]);
```

Or, what you did with `$request->flash()` also works.

**Comment by susanBuck** [comment]
Correction to my above post! 

The `redirect('/destination')->with($data)` method will in fact flash data to the session so it's available on the next request (via `$request->session()->get($data)`.

*However*, it will not be retrievable via the `old` method. 

(I did some testing and observed that the old method stores/expects the data to be nested in a session variable called `_old_input`, and a `redirect()->with(data)` does not put data here)

If validation passes, and you still want access to the old form data using the `old` helper method, you have to do  either one of the following:

### Option 1)
Exactly what @jessupjs said: Invoke `$request->flash();` before the redirect

### Option 2)
Chain the `withInput` method to your redirect: `return redirect('/destination')->withInput()`

In the documentation on the [old helper method](https://laravel.com/docs/5.7/helpers#method-old), there's a link to ["old input"](https://laravel.com/docs/5.7/requests#old-input) which explains all of this. I should have read deeper into that and done a test before making my previous replies. Sorry for the confusion. :-)

**Comment by hemantbajpai** [comment]
thanks
