### ISSUE TITLE
How to sanitize dropdown form data

### ISSUE THREAD

**Issue by hemantbajpai** [susanBuck/dwa15-fall2018#89]
Hi,

Is this correct way to sanitize dropdown form data or i am missing something?

<select class='form-control' name='includeSpecialChar'>
    <option value='~' @if( old('includeSpecialChar', $includeSpecialChar) == '~') {{ 'selected' }} @endif>~</option>
</select>

Thanks

**Comment by jpersson74** [comment]
@hemantbajpai -

I did something similar to [this post](https://stackoverflow.com/questions/33141056/laravel-5-1-how-to-use-old-helper-on-blade-file-for-radio-inputs) on radio buttons to my dropdown.

**Comment by susanBuck** [comment]
@hemantbajpai Your code is not showing. Can you [update your post with markdown](https://github.com/susanBuck/dwa15-fall2018/issues/1) to correct this?

**Comment by hemantbajpai** [comment]
I think I understood this one. Thanks
