### ISSUE TITLE
Citing Sources

### ISSUE THREAD

**Issue by chantalthomas** [susanBuck/dwa15-fall2018#9]
Hello! I've copied and pasted some css for normalizing styles from a project that I completed for a  previous class. Do I need to cite this code? And if so how should we go about doing so?

**Comment by susanBuck** [comment]
Is the project from the previous class on Github? If so, I'd site the repo URL with a note.
If not, just a quick note will suffice.

**Comment by chantalthomas** [comment]
@susanBuck Thank you
