### ISSUE TITLE
Validation Messages Not Displaying

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#92]
Hi... I have reached the validation part of my project, and I am experiencing an error. I have researched it but can't seem to find why it is happening. When the user goes to the form and leave a field blank, I get this error screen. If they fill out the entire form, they get the returned calculation displayed. However, I am not able to figure out how to display the error messages since it keeps going to this output instead of displaying error messages on the form. In my display file, I do have this code. I am not sure if I did it correctly in Blade format so that could be part of the problem.

<img width="1238" alt="screen shot 2018-11-05 at 10 21 18 am" src="https://user-images.githubusercontent.com/35276882/48011097-8eef1a80-e0e4-11e8-96b9-4bd277edf49a.png">

``` 
div id='results'>
        @isset($petName, $size, $petAge)
            <p>{{ $petName }} is a(n) {{ $petAge }} and weighs {{ $size }} pound(s). {{ $petName }} needs {{ $results }} cup(s) of food per day.</p>
        @endisset
    </div> 
```

**Comment by pausman** [comment]
The offset error means that you are accessing an array value that does not exist you should have an if statement that if you have an error dont access the array and gives $results a default value.

In the view catch the errors and display the error
```
  @if(count($errors) > 0)
        <div class='alert alert-danger'>
           Please correct the errors above.
        </div>
    @endif

**Comment by cpowell1** [comment]
Thank you! That is what I have in my view file, but I think the problem is coming from my form controller file. Currently this is the code I have for that file. 

```
   public function index()
    {
        return view('home');
    }

    public function results(Request $request)
    {
        return view('home')->with([
            'petName' => $request->session()->get('petName', ''),
            'size' => $request->session()->get('size', ''),
            'petAge' => $request->session()->get('petAge', false),
            'results' => $request->session()->get('results'),
        ]);
    }

    public function infoProcess(Request $request)
    {
        $petName = $request->input('petName', '');
        $size = $request->input('size', null);
        $petAge = $request->input('petAge', false);

        $dogs = [
            'Puppy' => [
                '0-15' => '1/2',
                '16-25' => '1',
                '26-40' => '1.5',
                '41-60' => '2.4',
                '61-80' => '3.5',
                '81-100' => '4.5',
                '101' => '6'
            ],
            'Adult' => [
                '0-15' => '1',
                '16-25' => '1.',
                '26-40' => '2.5',
                '41-60' => '3.5',
                '61-80' => '4.5',
                '81-100' => '5.5',
                '101' => '6+'
            ],
            'Senior' => [
                '0-15' => '1/2',
                '16-25' => '1',
                '26-40' => '2',
                '41-60' => '3',
                '61-80' => '4',
                '81-100' => '5',
                '101' => '5.5'
            ],
        ];

        if (!$request->has($errors)) {
            $results = $dogs[$petAge][$size];
        }


        return redirect('/')->with([
            'petName' => $petName,
            'size' => $size,
            'petAge' => $petAge,
            'results' => $results,
        ]);
        }

        public
        function store(Request $request)
        {
            $request->validate([
                'petName' => 'required',
                'size' => 'required',
                'petAge' => 'required',
            ]);

            dump($request->all());

        }

}
```

I believe I am not correctly writing my if statement to show $results variable.

**Comment by pausman** [comment]
you have not validated your input?
```
$request->validate([
            'petname' => 'required',
           ....
        ]);

**Comment by susanBuck** [comment]
+1 to @pausman's note. Your controller does not appear to be invoking the validation method ([ref](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/validation.md#validating-the-request)).

**Comment by cpowell1** [comment]
Would that not be the same as the validation I have at the bottom in the store function? Does it need to be in the infoProcess section instead? Because I tried both and each are still giving me the debug bar stating that $errors isn't defined.

**Comment by cpowell1** [comment]
I moved it to the infoProcess function, and the errors show, but the $results is now taking me to the debug page. Mainly because it says the $errors variable is not defined. However, I thought $errors was a laravel preset variable?

```
class DogController extends Controller
{
    public function index()
    {
        return view('home');
    }

    public function results(Request $request)
    {
        return view('home')->with([
            'petName' => $request->session()->get('petName', ''),
            'size' => $request->session()->get('size', ''),
            'petAge' => $request->session()->get('petAge', false),
            'results' => $request->session()->get('results'),
        ]);
    }

    public function infoProcess(Request $request)
    {
        $petName = $request->input('petName', '');
        $size = $request->input('size', null);
        $petAge = $request->input('petAge', false);

        $dogs = [
            'Puppy' => [
                '0-15' => '1/2',
                '16-25' => '1',
                '26-40' => '1.5',
                '41-60' => '2.4',
                '61-80' => '3.5',
                '81-100' => '4.5',
                '101' => '6'
            ],
            'Adult' => [
                '0-15' => '1',
                '16-25' => '1.',
                '26-40' => '2.5',
                '41-60' => '3.5',
                '61-80' => '4.5',
                '81-100' => '5.5',
                '101' => '6+'
            ],
            'Senior' => [
                '0-15' => '1/2',
                '16-25' => '1',
                '26-40' => '2',
                '41-60' => '3',
                '61-80' => '4',
                '81-100' => '5',
                '101' => '5.5'
            ],
        ];



        $request->validate([
            'petName' => 'required',
            'size' => 'required',
            'petAge' => 'required',
        ]);

        if ($request->has($errors)) {
           return 'Please fix the errors.';
        } else {
          $results = $dogs[$petAge][$size];
        }


        return redirect('/')->with([
            'petName' => $petName,
            'size' => $size,
            'petAge' => $petAge,
            'results' => $results,
        ]);
        }



}
```

**Comment by susanBuck** [comment]
@cpowell1 Yes, it's the similar validation code you had in the `store` method - but the error you were facing was happening in `infoProcess` where you were trying to use the data, so the validation needed to happen there, and you're correct in moving it there.

Can you update your repo w/ the latest changes and share the URL so I can directly test/debug on my end?

**Comment by cpowell1** [comment]
Yes, here is the URL: https://github.com/cpowell1/project3. I understand that now, and thank you both for taking the time to help me understand.

**Comment by susanBuck** [comment]
FYI For anyone watching this thread - @cpowell1 and I worked through the code in Slack - just had to do a little rearranging and we got things working.

Our discussion also lead to some fruitful examples of pre-filling inputs on errors, which you can read more about here: #94
