### ISSUE TITLE
Redirect/old() method issue

### ISSUE THREAD

**Issue by baugh20s** [susanBuck/dwa15-fall2018#93]
I'm having an issue with using the return redirect() suggestion from the lecture, in conjunction with the old() helper method.

I actually had it almost working without either of those, by using the following in my controller instead of return redirect:
return view ('collegeCost.index')

and not using the old() method. This works on my form when there are no errors. However, when there is an error, all the values displayed revert back to the most recent values entered when there were no errors, instead of just the most recently entered ones. (This is true right now on my prod site).

When I add the old() method to my view file (still using return view) and there are no errors, all inputted values with the old() method are totally removed from the form upon submission. If there are errors, it displays all of the inputted values as desired.

If I use return redirect in conjunction with the old() method, I can't figure out what to put for the destination. When I put a '/', it wipes everything when I submit; when I put the name of the view (and the directory it's in), I get a 404 upon submission. (The view is called index.blade.php and it's in the collegeCost directory, which is in the views directory; so I was putting '/collegeCost/index' as the destination).

Screenshot of the two different options in my controller (one commented out):
![return view versus redirect](https://user-images.githubusercontent.com/20144373/48037347-cfc54e80-e139-11e8-880f-03ef07e97c61.png)

**Comment by DoryAzar** [comment]
Sarah - I noticed that in the CollegeCalcController, in the index function you are using `$request->input` for `childName` and `collegeCostNow`. You are also setting `collegeCostFuture` to null. This is probably overriding the results from the results from the calcCost function. 

Use `$request->session()` for all your variables in the index function. Let the session dictate what the variables should be upon applying the calcCost function. 
The old function should work fine after that change, I think.

**Comment by baugh20s** [comment]
I realized the mistake with input versus session as I continued to look at it, and I've now updated the collegeCostFuture one as well (had trouble figuring out what that should be before, I thought it would be different since I was calculating it after submission) - I've pushed that to production.

However, when there are no errors, the values don't remain on the form; while not as necessary as when there's an error message, wouldn't it be helpful for users to see what they've entered to get the result?

**Comment by DoryAzar** [comment]
Good. That is the expected behaviour. Upon correct submission, the old function flushes the inputs. So in that case, you should use `old(‘variable_name', $variablename)` where $variablename ends up being the one taken from the session.

**Comment by susanBuck** [comment]
The `old` helper method only retains data from the form request if validation fails and does the redirect. 

If you just do a regular redirect, even if you pass data using the `with` method, the old data will not be accessible via the `old` method. 

To make data available via `old` after a "manual" redirect, you have to explicitly make it available via one of the approaches described here: [Old Input](https://laravel.com/docs/5.7/requests#old-input)

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
