### ISSUE TITLE
Prefilling examples (upon validation success or failure)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-fall2018#94]
I was just working with a student in Slack on pre-filling techniques with validation, and wanted to share some examples that might be helpful for others.

## Text input:
```php
<input type='text' name='amount'  value='{{ old('amount', $amount) }}'>
```

__Explanation__
If validation fails, `amount` will be available via `old` and that's what the value will be set to.

If `amount` in `old` is not available (because validation was successful), then it will default to the second argument`$amount`. 

(This assumes you've made `$amount` available to your view upon success, ala `return view()->with()`)

## Checkbox
```php
<input type='checkbox' name='roundUp' {{ (old('roundUp', $roundUp) ? 'checked' : '' }}>
```
Same idea as above, but we're using a ternary operator and evaluating `(old('roundUp', $roundUp)` as a boolean expression. If it's true, the blade echo shortcut will echo `checked`, otherwise it'll echo a blank string `''`.

## Dropdown:
```php
<select name='tip'>
            <option value=''>Choose one...</option>
            <option value='15' {{ (old('tip', $tip) == '15') ? 'selected' : '' }}>Okay</option>
            <option value='18' {{ (old('tip', $tip) == '18') ? 'selected' : '' }}>Good</option>
            <option value='20' {{ (old('tip', $tip) == '20') ? 'selected' : '' }}>Excellent</option>
</select>
```

__Explanation__
Same idea as the checkbox, but we echo `selected` instead of `checked`

## Points of reference
+ [PHP: Syntactic sugar](https://github.com/susanBuck/dwa15-fall2018/blob/master/php/syntactic-sugar.md) (for explanation of the ? : ternary operator)
+ [Laravel old helper method](https://laravel.com/docs/5.7/helpers#method-old)
+ [Laravel old input](https://laravel.com/docs/5.7/requests#old-input)

**Comment by T-Waddell** [comment]
Thank you for sharing this! Could you share any changes that need to be taken into account for radio buttons? I used code similar to the checkbox and dropdown, and it retains the value when validation fails, but not when the validation is successful. I double checked that my cadence variable is being passed along properly as part of the redirect and the form display function.

```php
<label><input type='radio' name='cadence' value='weekly' {{ (old('cadence', $cadence) == 'weekly') ? 'checked' : '' }}> Weekly</label>
<label><input type='radio' name='cadence' value='monthly' {{(old('cadence', $cadence) == 'monthly') ? 'checked' : ''}}> Monthly</label>
```

**Comment by susanBuck** [comment]
@T-Waddell Radio buttons can be prefilled just like checkboxes - and the code you've provided looks correct.

You said you confirmed your $cadence variable is being passed along - not sure how you confirmed that, but here's what I'd do to make sure I'm 100% clear on the data the view is working with...

Right before your radio buttons, enter the following two temporary debug statements to dump to the page the value for `old('cadence', $cadence)` and, for good measure, `dump($cadence)`.

```php
<?php dump(old('cadence', $cadence)) ?>
<?php dump($cadence) ?>
<label><input type='radio' name='cadence' value='weekly' {{ (old('cadence', $cadence) == 'weekly') ? 'checked' : '' }}> Weekly</label>
<label><input type='radio' name='cadence' value='monthly' {{(old('cadence', $cadence) == 'monthly') ? 'checked' : ''}}> Monthly</label>
```

The first dump for `old('cadence', $cadence)` should be outputting either `weekly` or `monthly`. Is it?

**Comment by malrice** [comment]
Is there a validation for spaces? I searched the laravel pages and didn't seem to see anything. For example, I have a text space for Name, but whenever someone puts a full name like "John Smith" it comes back as an error because of the space. Am I doomed to have separate inputs for first and last names?

**Comment by T-Waddell** [comment]
@susanBuck Thank you! I had meant I checked over the code visually, but your advice helped me find that I had tweaked the value for better grammar when I displayed it on the page, and that was throwing off the pre-filling.

**Comment by susanBuck** [comment]
@malrice - There's no built-in rule for alpha + space, but you can create a custom rule.

There are 3 different approaches to creating custom validation rules which you can read about here:
https://laravel.com/docs/5.7/validation#custom-validation-rules.

As an example, here's the [closure](https://laravel.com/docs/5.7/validation#using-closures) approach used to validate that the title only contains letters and spaces:

```php
# Validate the request data
        $request->validate([
            'title' => ['required', function ($attribute, $value, $fail) {
                # If value does not contain only letters and spaces
                if (!preg_match('/^[\pL\s]+$/u', $value)) {
                    $fail('The '.$attribute.' field can only contain letters and spaces.');
                }
            }],
            'author' => 'required',
            'published_year' => 'required|digits:4',
            'cover_url' => 'required|url',
            'purchase_url' => 'required|url'
        ]);
```

You'll note the validation is done using a regular expression, which I grabbed from this StackOverflow post: [Laravel validation rule alpha cannot take whitespace](https://stackoverflow.com/questions/34099777/laravel-5-1-validation-rule-alpha-cannot-take-whitespace)

**Comment by susanBuck** [comment]
@T-Waddell Gotcha; Glad you got to the bottom of it!
