### ISSUE TITLE
Information flow between blade and Controller

### ISSUE THREAD

**Issue by dnoren32** [susanBuck/dwa15-fall2018#95]
Hello All,

I have a general question. How do we pass information from blade to Controller so it can be worked on. I have this form and I just can't figure out how to track the user data. I've gone through all the videos since the p2 for a second time and still can't figure it out.  I know it's last minute but any help would be realllllly appreciated. Thanks!

Here is my form
  ```
<form method='GET' action='/' id='assessment'>
            Name: <input type='text' name='name'>
            <br>
            Did you take your personality test? <input type='checkbox' name='taken' >
            <br>
            Which personality trait was strongest based on the assessment?: <select name='trait'>
                <option value=''>--</option>
                <option value='Dominance'>Dominance</option>
                <option value='Influence'>Influence</option>
                <option value='Steadiness'>Steadiness</option>
                <option value='Conscientiousness'>Conscientiousness</option>
        </select><br><br>

        <input type='submit' value='Learn More about Your Trait!' class='button button1'>
    </form>
```

**Comment by ccrane** [comment]
@dnoren32 Pass a **Request $request** parameter to your controller method, and then within the method you can use the following to get the value
**$trait =  $request->get('trait');**

**Comment by dnoren32** [comment]
@ccrane ok so just so I have this straight:

When a user enters the URL they are directed to a landing page based on the URL endings. Which page they get to depends on the route that is set up to handle that URL. The route then points to a controller and can (but doesn't have to) send information based on the URL ending along with it. The controller is where the magic happens. Based on the code written in the controller, it will eventually get passed to a view. The view is the show code. This is where we have our html which will display our form. Once the form loads, the code stops running and waits for the user to hit submit on the form. Once the user hits submit, the data gets sent to the controller via Request. This is where form validation and manipulation of the user data occurs. Once the controller does its thing with the code it responds by sending back to a view with the new/updated information. 

Is that generally speaking what's going on?

**Comment by susanBuck** [comment]
@dnoren32 Everything you've described is accurate, but I'd expound a bit on this step:

>> "Once the user hits submit, the data gets sent to the controller via Request."

Once the user hits submit, the form is submitted to the URL as specified by the form *action*, as either a GET or POST request (depending on the form *method*)

E.g.:
```php
<form method='GET' action='/books/search-process'>
```

The receiving URL (in this example, `/books/search-process`) should trigger a specific route, which should invoke a specific controller method - depending on how we've configured it in our routes file.

That controller method will have access to a Request object, which contains all of the data from the form.

```php
public function searchProcess(Request $request) {

    # This is where form validation and manipulation of the user data occurs. 
    # When done, it can redirect back to the route with the form, attaching any needed data as part of the redirect
}
```

I'd also clarify this line:

>> "Once the controller does its thing with the code it responds by sending back to a view with the new/updated information."

To be clear, it's sending back (redirecting) to a route, that triggers a controller method, that returns a view. So, effectively yes, we get "back" to our original view with the form, but I just wanted to clarify the language of what's actually happening. : )


For reference (b/c your original post mentioned you weren't able to locate this info) this is what you're looking for:

+ Video: [Week 8](https://dwa15.com/week/8) : [Part 3 - Forms with GET ("Search" feature)](https://www.youtube.com/embed/436c8bJm7XQ?rel=0&showinfo=0)
+ Notes: [Forms with GET](https://github.com/susanBuck/dwa15-fall2018/blob/master/laravel/forms-get.md)

**Comment by dnoren32** [comment]
@susanBuck thank you SO much for this summary and pointing out the lecture where you previously discussed this. I've had the flu this past couple days and I don't think the 103 fever helped with processing the info :D
