### ISSUE TITLE
Form not validating (even with validation code present)

### ISSUE THREAD

**Issue by chantalthomas** [susanBuck/dwa15-fall2018#96]
Hi All,

I have added the code below, just as in the notes, and my form is still being processed. Am I missing something? My form is using get and not post. Should that make a difference? 

```public function store(Request $request)
    {
        # Validate the request data
        $request->validate([
            'feet' => 'required|digits',
            'inches' => 'required|digits',
            'weight' => 'required|digits',
            'age' => 'required|digits',
            'gender' => 'required',
            'exerciseAmount' => 'required'
        ]);
    }
```
Thank you in advance!

**Comment by DoryAzar** [comment]
Chantal -
I just checked your code. Your code seems right. However, you have the `$request->validate` call in a function called `store` that you are never referencing. I would suggest that you put the `$request->validate` code in the very top of the `mifflinEquation` function. This should work.

**Comment by susanBuck** [comment]
@chantalthomas - The digits validation method expects a parameters specifying how many digits.
E.g. `digits:4`

Ref: https://laravel.com/docs/5.7/validation#rule-digits
![image](https://user-images.githubusercontent.com/237711/48168119-1773e380-e2bc-11e8-9b45-8d23fe4bdfff.png)

If you don't want to specify an exact length, you can switch to `digits_between:min,max` and specify a min/max.
