### ISSUE TITLE
Route to process form works on local but not on production

### ISSUE THREAD

**Issue by cpowell1** [susanBuck/dwa15-fall2018#97]
I have deployed my project to production, but I am getting an error when I submit the form that the "/info-process" URL was not found. On my local host, the form was working fine and redirected back to the form page. Any ideas why this might happen?

**Comment by DoryAzar** [comment]
yes. best guess would be that you need to change the APP_URL in the .env file.
If you are using the local one, this might be the source of the problem

**Comment by cpowell1** [comment]
*I adjusted the .htaccess file and it is now working!
