### ISSUE TITLE
Default document root for Digital Ocean server

### ISSUE THREAD

**Issue by Sud-B** [susanBuck/dwa15-fall2018#98]
Is there any way to get the default file for this? I've accidentally made the wrong changes here and saved them  so the structure has changed and my url won't work.

**Comment by susanBuck** [comment]
Check out the notes on [production domains](https://github.com/susanBuck/dwa15-fall2018/blob/master/servers-and-git/production-domain.md). There's a link in there to a template of the original `000-default.conf` file on DigitalOcean (search for "original")

**Comment by Sud-B** [comment]
Thank you Susan. It worked!
